### ISSUE TITLE
AnsibleUndefinedVariable

### ISSUE THREAD

**Issue by pawankumarsing49** [RedHatOfficial/ocp4-helpernode#10]
I am getting the below error while running the playbook with these commands
 ansible-playbook -e vars.yaml tasks/main.yml
my vars.yaml file is 
disk: vda
helper:
  name: "helper"
  ipaddr: "192.168.2.109"
  networkifacename: "enp0s3"
dns:
  domain: "openshift.example.com"
  clusterid: "ocp4"
  forwarder1: "8.8.8.8"
  forwarder2: "8.8.4.4"
dhcp:
  router: "192.168.2.1"
  bcast: "192.168.2.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.2.10"
  poolend: "192.168.2.30"
  ipid: "192.168.2.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.2.108"
  macaddr: "08:00:27:07:0b:3f"
masters:
  - name: "master"
    ipaddr: "192.168.2.115"
    macaddr: "08:00:27:00:be:7d"
  - name: "master2"
    ipaddr: "192.168.2.121"
    macaddr: " 08:00:27:2d:b6:26"
  - name: "master3"
    ipaddr: "192.168.2.122"
    macaddr: "08:00:27:df:7b:d2"
workers:
  - name: "worker0"
    ipaddr: "192.168.7.11"
    macaddr: "52:54:00:f4:26:a1"
 
and error is 

[root@helper ocp4-helpernode]# ansible-playbook -e vars.yaml tasks/main.yml

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Install needed packages] *************************************************
ok: [localhost]

TASK [Install packages for DHCP/PXE install] ***********************************
ok: [localhost]

TASK [Write out dhcp file] *****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dhcp' is undefined"}
        to retry, use: --limit @/root/ocp4-helpernode/tasks/main.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1

and I configured static IP to all my nodes worker, master, and bootstrap. 
Please suggest if i am doing any wrong steps. if not, please help in this issue.

Help is appreciated
Thanks

**Comment by pawankumarsing49** [comment]
Following the git hub docs
https://github.com/RedHatOfficial/ocp4-helpernode

**Comment by pawankumarsing49** [comment]
Above issue is resolved now, however facing issue with DNS

TASK [Write out named file] ****************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dns' is undefined"}
        to retry, use: --limit @/root/ocp4-helpernode/tasks/main.retry

**Comment by christianh814** [comment]
Can you format your `vars.yaml`? Or at least post it in fpaste.org?

**Comment by christianh814** [comment]
@pawankumarsing49 Did you ever figure this out?

**Comment by pawankumarsing49** [comment]
@christianh814 Yes, its resolved now. The issue is with DNS entries, for ease I have used nip.io names entries.
Thanks for your reply.
