### ISSUE TITLE
Bare metal install: PXE Boot not working on Intel NUCs

### ISSUE THREAD

**Issue by snimmo-redhat** [RedHatOfficial/ocp4-helpernode#101]
I get all the way through the install instances part. https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/bmquickstart.md#install-instances

I'm setting the Intel NUCs BIOs in the following way: 
- Disable secure boot
- Enable UEFI boot
- Boot Option #1: UEFI: PXE IPv4 Intel(R) Ethernet, disable the others
- Uncheck all of the Fast Boot, Boot Network Devices Last, etc.

The NUC will get to the point of: 
"Checking media presence"
"Media Present"
"Start PXE over IPv4 on MAC: xxxxxxx"

and after ~1 min or so, it will error out with "A bootable device has not been detected". 

I've double checked the install and all of the files are in place, the webserver is running and serving the necessary files, etc. 

I have noticed other PXE boot tutorials that the filename mentioned in the DHCP config is always something like 'BOOTX64.efi'. 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/preparing-for-a-network-install_installing-rhel-as-an-experienced-user#configuring-a-tftp-server-for-uefi-based-clients_preparing-for-a-network-install

Does the bare metal not support UEFI PXE boot?

**Comment by christianh814** [comment]
> Does the bare metal not support UEFI PXE boot?

Although the OpenShift Image file does support UEFI boot, the HelperNode isn't set up to do so in the way TFTP is configured. This is definitely  something that needs to be updated. Thank you for the catch!

**Comment by snimmo-redhat** [comment]
Let me take a look at how we might be able to enhance this. The PXE default config could add another flag for UEFI boot.

pxe:
  uefi_boot: true

??

**Comment by christianh814** [comment]
> Let me take a look at how we might be able to enhance this. The PXE default config could add another flag for UEFI boot.
> 
> pxe:
> uefi_boot: true
> 
> ??

Well according to the [RHEL Doc](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/preparing-for-a-network-install_installing-rhel-as-an-experienced-user#configuring-a-tftp-server-for-uefi-based-clients_preparing-for-a-network-install) it looks like you can do both.

I think exploring how we can get both is a good first step. If we can't, yeah we would need to set an option like that.

**Comment by christianh814** [comment]
cc: @therevoman

**Comment by therevoman** [comment]
I believe Christian is correct that it's possible to do both.  Right now we are only using the `syslinux` package and uefi requires another with the files landing under `/var/lib/tftpboot`

**Comment by therevoman** [comment]
Might have to use a flag, I forgot that BIOS uses `linux` and EFI uses `linuxefi` in the grub config.

**Comment by christianh814** [comment]
Should be in [devel](https://github.com/RedHatOfficial/ocp4-helpernode/pull/196) now
