### ISSUE TITLE
PXE boot: "unable to locate configuration files"

### ISSUE THREAD

**Issue by markusFehling** [RedHatOfficial/ocp4-helpernode#106]
Running on ESX, DHCP works, IP addresses (own, router, dhcp) are assigned.
Was working with a pull of June.

**Comment by christianh814** [comment]
Might be related to #101 ...are you using UEFI/Secure Boot?

**Comment by markusFehling** [comment]
Hi, no UEFI, just BIOS

**Comment by christianh814** [comment]
@markusFehling I've done various test today (on the `devel` branch) and it's working.

Can you...

1) Try the devel branch? There are minor changes but changes nonetheless
2) Can you post your `vars.yaml` file you're using?

Thanks!

**Comment by christianh814** [comment]
Also take a look at  #92 ...do you think you can add `ip=dhcp` or ` ip=<your interface name>:dhcp` and see if that makes it boot? (I'm just curious)

**Comment by markusFehling** [comment]
Hi Team, thanks.
It did work in June ;-) 
Here my vars.yaml:

`---
disk: sda
helper:
  name: "helper"
  ipaddr: "192.168.1.10"
dns:
  domain: "fritz.box"
  clusterid: "ocp4"
  forwarder1: "192.168.1.1"
dhcp:
  router: "192.168.1.1"
  bcast: "192.168.1.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.1.30"
  poolend: "192.168.1.100"
  ipid: "192.168.1.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.1.20"
  macaddr: "00:0C:29:DD:EA:C0"
masters:
  - name: "master0"
    ipaddr: "192.168.1.21"
    macaddr: "00:0C:29:DD:EA:C1"
  - name: "master1"
    ipaddr: "192.168.1.22"
    macaddr: "00:0C:29:DD:EA:C2"
  - name: "master2"
    ipaddr: "192.168.1.23"
    macaddr: "00:0C:29:DD:EA:C3"
workers:
  - name: "worker0"
    ipaddr: "192.168.1.24"
    macaddr: "00:0C:29:DD:EA:C4"
  - name: "worker1"
    ipaddr: "192.168.1.25"
    macaddr: "00:0C:29:DD:EA:C5"
  - name: "worker2"
    ipaddr: "192.168.1.26"
    macaddr: "00:0C:29:DD:EA:C6"
`

**Comment by markusFehling** [comment]
I am sorry,looks like my  "insert code" does not format as code ...

**Comment by christianh814** [comment]
Should be fixed by #127
