### ISSUE TITLE
Please add NTP server option to the vars.yaml and the dhcp server config files

### ISSUE THREAD

**Issue by gefrickel** [RedHatOfficial/ocp4-helpernode#109]
Hi,

choosing proxified deployment leads to a cluster that cannot reach the .rhel.pool.ntp.org NTP servers. Specifying custom NTP servers within the setup would address this issue. Please allow the specification of NTP servers into the vars.yaml and subsequently pick them up in the DHCP servers config files.

Greetings.

**Comment by christianh814** [comment]
@gefrickel This was already in place by #67 

The caveat is that the playbook only creates the machineconfig for you and it's up to you to configure it. We just haven't documented how to use it yet.

Leaving this open as a reminder to document how to do this.

**Comment by christianh814** [comment]
Information about [NTP configuration](https://github.com/RedHatOfficial/ocp4-helpernode/blob/devel/docs/vars-doc.md#ntp-configuration) is now in devel
