### ISSUE TITLE
Helm client cli installation is specific to amd64 and changes are required for installing the ppc64le binary on powervm environment for helper node

### ISSUE THREAD

**Issue by arcprabh** [RedHatOfficial/ocp4-helpernode#116]
The below part of the code that is recently added to install helm cli for amd64 and is not applicable for ppc64le. 

Changes required:

1) Add support to install helm cli specific to ppc64le environment.
2) We need to have an additional check to install the amd64 helm binary only on non ppc64le environment. 

File location - https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/tasks/main.yml

 - name: Copy helm cli to bin directory
    copy:
      src: /usr/local/src/helm/linux-amd64/helm 
      dest: /usr/local/bin/helm
      owner: root
      group: root
      mode: '0755'
      remote_src: true

Changes suggested 

1) Add condition when below code is run

 - name: Copy helm cli to bin directory
    copy:
      src: /usr/local/src/helm/linux-amd64/helm 
      dest: /usr/local/bin/helm
      owner: root
      group: root
      mode: '0755'
      remote_src: true
when: not ppc64le ==> Include this new condition

2) Include this new path for ppc64le with condition check

  - name: Copy helm cli to bin directory
    copy:
      src: /usr/local/src/helm/linux-ppc64le/helm
      dest: /usr/local/bin/helm
      owner: root
      group: root
      mode: '0755'
      remote_src: true
when: ppc64le

Note - We are working on  these changes for the ppc64le platform and will submit it once done.

**Comment by christianh814** [comment]
Good catch. Does helm have a PPC binary? If not this can be a quick fix by adding

`when: not ppc64le`

**Comment by Prajyot-Parab** [comment]
@christianh814 yes here https://get.helm.sh/helm-v3.2.4-linux-ppc64le.tar.gz

**Comment by christianh814** [comment]
@Prajyot-Parab 

Ah okay. So there needs to be some logic when specifying a PPC install. I would like to avoid having another var, but also don't mind it if it's unavoidable.

**Comment by christianh814** [comment]
Fixed in `devel`
