### ISSUE TITLE
RFE: When you mirror the registry, a snippet of the imageContentSources should be saved somewhere

### ISSUE THREAD

**Issue by christianh814** [RedHatOfficial/ocp4-helpernode#118]
When you mirror the registry, a snippet of the `imageContentSources` config should be saved to a file somewhere, where someone can use it when building their `install-config.yaml` file.

I deally it should be placed somewhere in the playbook repo dir. Example:

```
~/ocp4-helpernode/postrun-outputs
```

**Comment by christianh814** [comment]
@Prajyot-Parab
I know you originally wrote this, so I'm not sure if you'd like to take a stab at this.

**Comment by Prajyot-Parab** [comment]
@christianh814 I will take a look at this.

**Comment by christianh814** [comment]
Fixed by #124
