### ISSUE TITLE
Bootstrap Node Boot Issues : Unable to locate configuration file

### ISSUE THREAD

**Issue by ksingh7** [RedHatOfficial/ocp4-helpernode#129]
The bootstrap node, gets the IP from DHCP but it throws PXE configuration error and does not boot. Rest other nodes 3 x Masters + 3 x workers, boots perfectly fine. I tried this multiple time by cleaning all ignition files but no luck.

![image](https://user-images.githubusercontent.com/9701902/88542501-26706b80-d034-11ea-97ad-df4a6813672b.png)

- After that i booted the bootstrp node from CoreOS image and edited the kernel parameters with install and ignition files and that booted just fine. See below

![image](https://user-images.githubusercontent.com/9701902/88542728-836c2180-d034-11ea-8b16-896186b8f364.png)

- Its fetching the ignition/bios file from the TFTP server.

![image](https://user-images.githubusercontent.com/9701902/88542804-a565a400-d034-11ea-960d-75356542c700.png)

**Comment by ksingh7** [comment]
@christianh814  per our discussion this is the issue.

**Comment by christianh814** [comment]
@ksingh7 What does `ls -l /var/lib/tftpboot/pxelinux.cfg/` show? Is the bootstrap listed there? (it'll be in the form of a mac adddress) If so, what does that file look like?

The `Unable to locate configuration file` message means it's unable to locate the configuration file in `/var/lib/tftpboot/pxelinux.cfg/` so maybe there's a typo or that file didn't get generated.

**Comment by ksingh7** [comment]
i verified that and there was infact the cofig file present in /var/lib/tftpboot/pxelinux.cfg/ and i double checked the configuration and it was all good.  

I have purged the setup now , but i plan to do that again and will share the actual contents of the fille

**Comment by christianh814** [comment]
@ksingh7 Since you chatted me that this was a vbox/ocp issue (and not the helpernode), I'm going to close this. I'm linking the BZ since it might be helpful to others

https://bugzilla.redhat.com/show_bug.cgi?id=1796491
