### ISSUE TITLE
OKD Support?

### ISSUE THREAD

**Issue by victorhooi** [RedHatOfficial/ocp4-helpernode#130]
Does anybody know if helpernode currently works with OKD out of the box?

If not, what would be involved in having it support OKD?

(Trying to setup a small 3-node OKD cluster for learning, this seems like an awesome fit, but the docs seem to imply it's for paid OCP only?)

**Comment by christianh814** [comment]
Hi @victorhooi , yes the HelperNode is pretty agnostic. Installation is just done with PXE and whatever files are provided to it.

In your `vars.yaml` file, you can specify which artifacts to use. [Read the documentation](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/vars-doc.md#specifying-artifacts) for more info. If you're using the DHCP method, you can just point these to the OKD artifacts.

I haven't tried it myself, but it should "just work".

**Comment by christianh814** [comment]
@victorhooi Have you tried installing OKD?

**Comment by christianh814** [comment]
Closing this. If you run into a problem, please feel free to open up another issue
