### ISSUE TITLE
Problem accessing cluster from web console  

### ISSUE THREAD

**Issue by rachmatowicz** [RedHatOfficial/ocp4-helpernode#138]
Everything is working fine for me, except accessing the cluster from the web console. 
After the installation has completed, I see the banner:
> [root@helper ocp4]# openshift-install wait-for install-complete
> INFO Waiting up to 30m0s for the cluster at https://api.ocp4.example.com:6443 to initialize... 
> INFO Waiting up to 10m0s for the openshift-console route to be created... 
> INFO Install complete!                            
> INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/root/ocp4/auth/kubeconfig' 
> INFO Access the OpenShift web-console here: https://console-openshift-console.apps.ocp4.example.com 
> INFO Login to the console with user: "kubeadmin", and password: "RWPtz-482uP-YUa5N-yJ5EX" 
> INFO Time elapsed: 0s                             

When I performed the install on my RHEL 8 hypervisor, I used a vnc session to connect to the (remote) desktop of the hypervisor and ran all the tutorial commands from there. 

![remote-desktop](https://user-images.githubusercontent.com/484226/89955039-2a89b500-dc00-11ea-8ae4-fa23cd6fc6f5.png)

Accessing the HAProxy status page during the install works fine with the instance of firefox available on the RHEL 8 remote desktop using the URL http://192.168.7.77:9000

![HAProxy-status](https://user-images.githubusercontent.com/484226/89955149-602e9e00-dc00-11ea-85bf-ec77fab82e46.png)

However, I would also like to access the web console using the remote desktop version of firefox. I add an entry for the IP address for the web console domain name console-openshift-console.apps.ocp4.example.com (which is 192.168.7.77) to /etc/hosts on my hypervisor. The when I try to access the web console URL https://console-openshift-console.apps.ocp4.example.com using the remote desktop firefox instance, I see several things happening:

* firefox warns me that the server is presenting a certificate that cannot be verified (its a self-signed certificate generated by the Ingres Operator)

 ![warning](https://user-images.githubusercontent.com/484226/89954336-e0540400-dbfe-11ea-971d-3027c9dc7c47.png)

* I tell firefox I want to continue even though the certificate cannot be verified 

![accept-warning](https://user-images.githubusercontent.com/484226/89954586-61ab9680-dbff-11ea-8ce4-2e332322e584.png)

* I see for a moment (maybe 1/2 second) the web console screen appear:

![brief-encounter](https://user-images.githubusercontent.com/484226/89954625-74be6680-dbff-11ea-8434-a24c315ab101.png)

* the web console screen is then quickly replaced by a screen saying the application is not available  

 ![disappointment](https://user-images.githubusercontent.com/484226/89954664-8738a000-dbff-11ea-845f-3b501df051a3.png) 

The following URL comes from the last screen that I receive:
>  https://oauth-openshift.apps.ocp4.example.com/oauth/authorize?client_id=console&redirect_uri=https://console-openshift-console.apps.ocp4.example.com/auth/callback&response_type=code&scope=user:full&state=2b08188b

This latter URL seems to be related to the builtin OAuth server that the cluster uses, but i'm not sure what is going on here and why it is automatically blocking my journey to the web console.  

Has anyone else run into this issue? Am I doing something dumb?

**Comment by christianh814** [comment]
If  you're doing everything on your RHEL 8 hypervisor under `/etc/hosts` you may need to add the oauth FQDN as well (and also any other routes you may create).

I suggest you setting up DNSMasq. I [go over this](https://youtu.be/wZYx4_xBSUQ?t=1896) during the Twitch stream I did.

**Comment by rachmatowicz** [comment]
Excellent! That has worked to fix the issue. 

I added the domain name oauth-openshift.apps.ocp4.example.com to my /etc/hosts file for the IP address 192.168.7.77, then tried to access the web console again. After getting the same certificate validation warnings as before, I arrived at the login screen:

![Login](https://user-images.githubusercontent.com/484226/90141369-10a7b980-dd49-11ea-9ada-a2e73915b3a1.png)

and then managed to login with the credentials for kubeadmin:

![Success](https://user-images.githubusercontent.com/484226/90141457-24532000-dd49-11ea-8265-0b510477011f.png)

So, I suppose the moral of the story is that when interacting with OpenShift from a server outside the cluster network, there may be "hidden" URLs which are used (like the one used by the web browser to contact the OAuth authorization server to get an access token to access the resources in the cluster) which may not be resolvable from outside the cluster network. So using dnsmasq to forward DNS requests for domain names in apps.ocp4.example.com from the host to the helper DNS server is a fix for that. 

Thanks again, Christian.

**Comment by christianh814** [comment]
NP! Glad it worked out for you! :+1:

**Comment by rachmatowicz** [comment]
Just FYI: concerning setting up dnsmasq on my RHEL 8 hypervisor, I do not run NetworkManager and so don't really want to turn it on to make use of the dnsmasq plugin as described in the video. 

Instead, when an interface comes up, an instance of dhclient is started and it will modify the instance of /etc/resolv.conf, which will otherwise interfere with a local dnsmasq instance.

To work around this, you can configure dhclient to store the modifications it makes to /etc/resolv.conf to be written to /etc/resolv.conf.dhclient (by using a dhclient-enter-hook) and then get dnsmaq to read this file when it starts up (using the configuration option resolv-file).
