### ISSUE TITLE
ppc64le-ISOmaker

### ISSUE THREAD

**Issue by vsolasa** [RedHatOfficial/ocp4-helpernode#148]
Hi Team,

I happened to notice that you have isomaker for x86, do you have the steps involved for RHCOS on ppc64le? how can i customize the image for ppc64le? 

Link i found for iso maker is - https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/iso-maker.md

**Comment by christianh814** [comment]
I don't know if the steps to create an ISO for ppc64le would be the same/different. This would need to be investigated

cc: @chuckersjp for awareness

**Comment by christianh814** [comment]
Maybe @bpradipt and @Prajyot-Parab would like to take a stab at it.

**Comment by chuckersjp** [comment]
How are ppc64le images generated?  I don't seem to find them on mirror.openshift.com unless I am looking in the wrong place.

(later)  Never mind.  I WAS looking in the wrong place.

You would need to change `group_vars/all.yml` and update the image list at the very least.
Then update the URL for the location of the download as it looks like the site assumes a  default to x86_64

After that, what the actual image looks like on the inside and whether it will boot in the same fashion, that I don't
know and don't have an easy way to test.  The other modifications are probably trivial but I don't know if the ISO
would still work properly.

**Comment by vsolasa** [comment]
Thank you Chucker.. i can show you on how it will look internally.. 

[root@p10-helper mnt]# ls -ltr
total 9
-r--r--r--. 1 root root  370 Jul 15 07:54 README.md
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 images
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 System
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 ppc
-r--r--r--. 1 root root    0 Jul 15 08:49 mach_kernel
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 boot
[root@p10-helper mnt]# ls -ltrR
.:
total 9
-r--r--r--. 1 root root  370 Jul 15 07:54 README.md
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 images
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 System
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 ppc
-r--r--r--. 1 root root    0 Jul 15 08:49 mach_kernel
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 boot

./images:
total 97994
-r-xr-xr-x. 1 root root 26837285 Jul 15 08:49 vmlinuz
-r-xr-xr-x. 1 root root 73507372 Jul 15 08:49 initramfs.img

./System:
total 2
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 Library

./System/Library:
total 2
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 CoreServices

./System/Library/CoreServices:
total 169
-r--r--r--. 1 root root    236 Jul 15 08:49 SystemVersion.plist
-r--r--r--. 3 root root 155288 Jul 15 08:49 grub.elf
-r--r--r--. 1 root root  16632 Jul 15 08:49 BootX

./ppc:
total 15
dr-xr-xr-x. 1 root root  2048 Jul 15 08:49 chrp
-r--r--r--. 1 root root 12572 Jul 15 08:49 bootinfo.txt

./ppc/chrp:
total 0

./boot:
total 2
dr-xr-xr-x. 1 root root 2048 Jul 15 08:49 grub

./boot/grub:
total 185
-r-xr-xr-x. 1 root root    556 Jul 15 07:54 grub.cfg
dr-xr-xr-x. 1 root root   2048 Jul 15 08:49 roms
dr-xr-xr-x. 1 root root  28672 Jul 15 08:49 powerpc-ieee1275
-r--r--r--. 3 root root 155288 Jul 15 08:49 powerpc.elf
dr-xr-xr-x. 1 root root   2048 Jul 15 08:49 fonts

./boot/grub/roms:
total 0

./boot/grub/powerpc-ieee1275:
total 3013
-r--r--r--. 1 root root  89516 Jul 15 08:49 zfs.mod
-r--r--r--. 1 root root  10704 Jul 15 08:49 zfsinfo.mod
-r--r--r--. 1 root root  10112 Jul 15 08:49 zfscrypt.mod
-r--r--r--. 1 root root  37364 Jul 15 08:49 xzio.mod
-r--r--r--. 1 root root   2912 Jul 15 08:49 xnu_uuid_test.mod
-r--r--r--. 1 root root   3436 Jul 15 08:49 xnu_uuid.mod
-r--r--r--. 1 root root  16364 Jul 15 08:49 xfs.mod
-r--r--r--. 1 root root   5608 Jul 15 08:49 videotest.mod
-r--r--r--. 1 root root   3296 Jul 15 08:49 videotest_checksum.mod
-r--r--r--. 1 root root  13992 Jul 15 08:49 video.mod
-r--r--r--. 1 root root     12 Jul 15 08:49 video.lst
-r--r--r--. 1 root root   6528 Jul 15 08:49 videoinfo.mod
-r--r--r--. 1 root root  54376 Jul 15 08:49 video_fb.mod
-r--r--r--. 1 root root   7924 Jul 15 08:49 video_colors.mod
-r--r--r--. 1 root root   2456 Jul 15 08:49 version.mod
-r--r--r--. 1 root root  24500 Jul 15 08:49 verify.mod
-r--r--r--. 1 root root  13064 Jul 15 08:49 ufs2.mod
-r--r--r--. 1 root root  13136 Jul 15 08:49 ufs1.mod
-r--r--r--. 1 root root  12288 Jul 15 08:49 ufs1_be.mod
-r--r--r--. 1 root root  19480 Jul 15 08:49 udf.mod
-r--r--r--. 1 root root   1780 Jul 15 08:49 true.mod
-r--r--r--. 1 root root   3420 Jul 15 08:49 tr.mod
-r--r--r--. 1 root root   1752 Jul 15 08:49 trig.mod
-r--r--r--. 1 root root   2320 Jul 15 08:49 time.mod
-r--r--r--. 1 root root   8928 Jul 15 08:49 tga.mod
-r--r--r--. 1 root root  10240 Jul 15 08:49 tftp.mod
-r--r--r--. 1 root root   3300 Jul 15 08:49 testspeed.mod
-r--r--r--. 1 root root  11676 Jul 15 08:49 test.mod
-r--r--r--. 1 root root   4264 Jul 15 08:49 testload.mod
-r--r--r--. 1 root root   1776 Jul 15 08:49 test_blockarg.mod
-r--r--r--. 1 root root   8168 Jul 15 08:49 terminal.mod
-r--r--r--. 1 root root     54 Jul 15 08:49 terminal.lst
-r--r--r--. 1 root root   5872 Jul 15 08:49 tar.mod
-r--r--r--. 1 root root  36300 Jul 15 08:49 syslinuxcfg.mod
-r--r--r--. 1 root root   1620 Jul 15 08:49 suspend.mod
-r--r--r--. 1 root root   3120 Jul 15 08:49 strtoull_test.mod
-r--r--r--. 1 root root  16144 Jul 15 08:49 squash4.mod
-r--r--r--. 1 root root   3584 Jul 15 08:49 sleep_test.mod
-r--r--r--. 1 root root   2884 Jul 15 08:49 sleep.mod
-r--r--r--. 1 root root   8320 Jul 15 08:49 signature_test.mod
-r--r--r--. 1 root root   5012 Jul 15 08:49 shift_test.mod
-r--r--r--. 1 root root  10388 Jul 15 08:49 sfs.mod
-r--r--r--. 1 root root   2440 Jul 15 08:49 setjmp_test.mod
-r--r--r--. 1 root root    868 Jul 15 08:49 setjmp.mod
-r--r--r--. 1 root root  13584 Jul 15 08:49 serial.mod
-r--r--r--. 1 root root   5244 Jul 15 08:49 search.mod
-r--r--r--. 1 root root   5260 Jul 15 08:49 search_label.mod
-r--r--r--. 1 root root   5512 Jul 15 08:49 search_fs_uuid.mod
-r--r--r--. 1 root root   5380 Jul 15 08:49 search_fs_file.mod
-r--r--r--. 1 root root   9956 Jul 15 08:49 scsi.mod
-r--r--r--. 1 root root   8292 Jul 15 08:49 romfs.mod
-r--r--r--. 1 root root  28056 Jul 15 08:49 relocator.mod
-r--r--r--. 1 root root  20132 Jul 15 08:49 reiserfs.mod
-r--r--r--. 1 root root 126056 Jul 15 08:49 regexp.mod
-r--r--r--. 1 root root   1688 Jul 15 08:49 reboot.mod
-r--r--r--. 1 root root   2172 Jul 15 08:49 read.mod
-r--r--r--. 1 root root   3844 Jul 15 08:49 raid6rec.mod
-r--r--r--. 1 root root   1976 Jul 15 08:49 raid5rec.mod
-r--r--r--. 1 root root   3988 Jul 15 08:49 progress.mod
-r--r--r--. 1 root root   3900 Jul 15 08:49 procfs.mod
-r--r--r--. 1 root root   4548 Jul 15 08:49 probe.mod
-r--r--r--. 1 root root   2924 Jul 15 08:49 priority_queue.mod
-r--r--r--. 1 root root  15888 Jul 15 08:49 png.mod
-r--r--r--. 1 root root   2992 Jul 15 08:49 pbkdf2_test.mod
-r--r--r--. 1 root root   1880 Jul 15 08:49 pbkdf2.mod
-r--r--r--. 1 root root   4932 Jul 15 08:49 password_pbkdf2.mod
-r--r--r--. 1 root root   2808 Jul 15 08:49 password.mod
-r--r--r--. 1 root root   8164 Jul 15 08:49 parttool.mod
-r--r--r--. 1 root root     17 Jul 15 08:49 parttool.lst
-r--r--r--. 1 root root   2740 Jul 15 08:49 part_sunpc.mod
-r--r--r--. 1 root root   2520 Jul 15 08:49 part_sun.mod
-r--r--r--. 1 root root   3052 Jul 15 08:49 part_plan.mod
-r--r--r--. 1 root root   3976 Jul 15 08:49 part_msdos.mod
-r--r--r--. 1 root root    111 Jul 15 08:49 partmap.lst
-r--r--r--. 1 root root   3848 Jul 15 08:49 part_gpt.mod
-r--r--r--. 1 root root   2320 Jul 15 08:49 part_dvh.mod
-r--r--r--. 1 root root   2908 Jul 15 08:49 part_dfly.mod
-r--r--r--. 1 root root   5040 Jul 15 08:49 part_bsd.mod
-r--r--r--. 1 root root   3136 Jul 15 08:49 part_apple.mod
-r--r--r--. 1 root root   2820 Jul 15 08:49 part_amiga.mod
-r--r--r--. 1 root root   2640 Jul 15 08:49 part_acorn.mod
-r--r--r--. 1 root root  11048 Jul 15 08:49 ofnet.mod
-r--r--r--. 1 root root   2108 Jul 15 08:49 offsetio.mod
-r--r--r--. 1 root root   4912 Jul 15 08:49 odc.mod
-r--r--r--. 1 root root  23696 Jul 15 08:49 ntfs.mod
-r--r--r--. 1 root root   9696 Jul 15 08:49 ntfscomp.mod
-r--r--r--. 1 root root 235676 Jul 15 08:49 normal.mod
-r--r--r--. 1 root root  15552 Jul 15 08:49 nilfs2.mod
-r--r--r--. 1 root root   5380 Jul 15 08:49 newc.mod
-r--r--r--. 1 root root 132696 Jul 15 08:49 net.mod
-r--r--r--. 1 root root   3292 Jul 15 08:49 mul_test.mod
-r--r--r--. 1 root root   3736 Jul 15 08:49 msdospart.mod
-r--r--r--. 1 root root  68868 Jul 15 08:49 mpi.mod
-r--r--r--. 1 root root   2625 Jul 15 08:49 modinfo.sh
-r--r--r--. 1 root root   3697 Jul 15 08:49 moddep.lst
-r--r--r--. 1 root root   8564 Jul 15 08:49 minix.mod
-r--r--r--. 1 root root   8088 Jul 15 08:49 minix_be.mod
-r--r--r--. 1 root root   8916 Jul 15 08:49 minix3.mod
-r--r--r--. 1 root root   8504 Jul 15 08:49 minix3_be.mod
-r--r--r--. 1 root root   8932 Jul 15 08:49 minix2.mod
-r--r--r--. 1 root root   8464 Jul 15 08:49 minix2_be.mod
-r--r--r--. 1 root root   6336 Jul 15 08:49 minicmd.mod
-r--r--r--. 1 root root   4568 Jul 15 08:49 memrw.mod
-r--r--r--. 1 root root   3392 Jul 15 08:49 memdisk.mod
-r--r--r--. 1 root root   3312 Jul 15 08:49 mdraid1x.mod
-r--r--r--. 1 root root   3172 Jul 15 08:49 mdraid09.mod
-r--r--r--. 1 root root   3052 Jul 15 08:49 mdraid09_be.mod
-r--r--r--. 1 root root  18104 Jul 15 08:49 macho.mod
-r--r--r--. 1 root root   5704 Jul 15 08:49 macbless.mod
-r--r--r--. 1 root root  10904 Jul 15 08:49 lzopio.mod
-r--r--r--. 1 root root  11996 Jul 15 08:49 lvm.mod
-r--r--r--. 1 root root  11248 Jul 15 08:49 luks.mod
-r--r--r--. 1 root root   6292 Jul 15 08:49 ls.mod
-r--r--r--. 1 root root   2516 Jul 15 08:49 lsmmap.mod
-r--r--r--. 1 root root   4920 Jul 15 08:49 loopback.mod
-r--r--r--. 1 root root  12696 Jul 15 08:49 loadenv.mod
-r--r--r--. 1 root root  16840 Jul 15 08:49 linux.mod
-r--r--r--. 1 root root  13848 Jul 15 08:49 ldm.mod
-r--r--r--. 1 root root   2720 Jul 15 08:49 keystatus.mod
-r--r--r--. 1 root root  14536 Jul 15 08:49 jpeg.mod
-r--r--r--. 1 root root  14300 Jul 15 08:49 jfs.mod
-r--r--r--. 1 root root  17648 Jul 15 08:49 iso9660.mod
-r--r--r--. 1 root root   3416 Jul 15 08:49 increment.mod
-r--r--r--. 1 root root  10388 Jul 15 08:49 ieee1275_fb.mod
-r--r--r--. 1 root root  11028 Jul 15 08:49 http.mod
-r--r--r--. 1 root root  15540 Jul 15 08:49 hfsplus.mod
-r--r--r--. 1 root root   5480 Jul 15 08:49 hfspluscomp.mod
-r--r--r--. 1 root root  13476 Jul 15 08:49 hfs.mod
-r--r--r--. 1 root root   4636 Jul 15 08:49 hexdump.mod
-r--r--r--. 1 root root   4120 Jul 15 08:49 help.mod
-r--r--r--. 1 root root   1468 Jul 15 08:49 hello.mod
-r--r--r--. 1 root root   8940 Jul 15 08:49 hashsum.mod
-r--r--r--. 1 root root   1676 Jul 15 08:49 halt.mod
-r--r--r--. 1 root root  16588 Jul 15 08:49 gzio.mod
-r--r--r--. 1 root root   6332 Jul 15 08:49 gptsync.mod
-r--r--r--. 1 root root  23148 Jul 15 08:49 gfxterm.mod
-r--r--r--. 1 root root   7212 Jul 15 08:49 gfxterm_menu.mod
-r--r--r--. 1 root root   4452 Jul 15 08:49 gfxterm_background.mod
-r--r--r--. 1 root root  88112 Jul 15 08:49 gfxmenu.mod
-r--r--r--. 1 root root   9508 Jul 15 08:49 gettext.mod
-r--r--r--. 1 root root  10544 Jul 15 08:49 geli.mod
-r--r--r--. 1 root root  37124 Jul 15 08:49 gcry_whirlpool.mod
-r--r--r--. 1 root root  99388 Jul 15 08:49 gcry_twofish.mod
-r--r--r--. 1 root root  22680 Jul 15 08:49 gcry_tiger.mod
-r--r--r--. 1 root root  11712 Jul 15 08:49 gcry_sha512.mod
-r--r--r--. 1 root root   6860 Jul 15 08:49 gcry_sha256.mod
-r--r--r--. 1 root root   9352 Jul 15 08:49 gcry_sha1.mod
-r--r--r--. 1 root root  58928 Jul 15 08:49 gcry_serpent.mod
-r--r--r--. 1 root root  34812 Jul 15 08:49 gcry_seed.mod
-r--r--r--. 1 root root   2932 Jul 15 08:49 gcry_rsa.mod
-r--r--r--. 1 root root  12240 Jul 15 08:49 gcry_rmd160.mod
-r--r--r--. 1 root root  27356 Jul 15 08:49 gcry_rijndael.mod
-r--r--r--. 1 root root   5584 Jul 15 08:49 gcry_rfc2268.mod
-r--r--r--. 1 root root   6424 Jul 15 08:49 gcry_md5.mod
-r--r--r--. 1 root root   5288 Jul 15 08:49 gcry_md4.mod
-r--r--r--. 1 root root   6028 Jul 15 08:49 gcry_idea.mod
-r--r--r--. 1 root root   3388 Jul 15 08:49 gcry_dsa.mod
-r--r--r--. 1 root root  49780 Jul 15 08:49 gcry_des.mod
-r--r--r--. 1 root root  12756 Jul 15 08:49 gcry_crc.mod
-r--r--r--. 1 root root  32512 Jul 15 08:49 gcry_cast5.mod
-r--r--r--. 1 root root  90236 Jul 15 08:49 gcry_camellia.mod
-r--r--r--. 1 root root  14120 Jul 15 08:49 gcry_blowfish.mod
-r--r--r--. 1 root root   2812 Jul 15 08:49 gcry_arcfour.mod
-r--r--r--. 1 root root  45044 Jul 15 08:49 functional_test.mod
-r--r--r--. 1 root root    219 Jul 15 08:49 fs.lst
-r--r--r--. 1 root root   6292 Jul 15 08:49 fshelp.mod
-r--r--r--. 1 root root  27448 Jul 15 08:49 font.mod
-r--r--r--. 1 root root  31508 Jul 15 08:49 file.mod
-r--r--r--. 1 root root  12224 Jul 15 08:49 fat.mod
-r--r--r--. 1 root root  16704 Jul 15 08:49 f2fs.mod
-r--r--r--. 1 root root  14648 Jul 15 08:49 ext2.mod
-r--r--r--. 1 root root   1856 Jul 15 08:49 exfctest.mod
-r--r--r--. 1 root root  11748 Jul 15 08:49 exfat.mod
-r--r--r--. 1 root root   2104 Jul 15 08:49 eval.mod
-r--r--r--. 1 root root   5928 Jul 15 08:49 escc.mod
-r--r--r--. 1 root root  10872 Jul 15 08:49 elf.mod
-r--r--r--. 1 root root   3056 Jul 15 08:49 echo.mod
-r--r--r--. 1 root root   2888 Jul 15 08:49 dm_nv.mod
-r--r--r--. 1 root root  12016 Jul 15 08:49 div_test.mod
-r--r--r--. 1 root root   1580 Jul 15 08:49 div.mod
-r--r--r--. 1 root root   4980 Jul 15 08:49 disk.mod
-r--r--r--. 1 root root  24324 Jul 15 08:49 diskfilter.mod
-r--r--r--. 1 root root   6848 Jul 15 08:49 datetime.mod
-r--r--r--. 1 root root   3456 Jul 15 08:49 date.mod
-r--r--r--. 1 root root   2544 Jul 15 08:49 datehook.mod
-r--r--r--. 1 root root   3708 Jul 15 08:49 ctz_test.mod
-r--r--r--. 1 root root   9640 Jul 15 08:49 crypto.mod
-r--r--r--. 1 root root    936 Jul 15 08:49 crypto.lst
-r--r--r--. 1 root root  20884 Jul 15 08:49 cryptodisk.mod
-r--r--r--. 1 root root   2992 Jul 15 08:49 crc64.mod
-r--r--r--. 1 root root   5064 Jul 15 08:49 cpio.mod
-r--r--r--. 1 root root   4920 Jul 15 08:49 cpio_be.mod
-r--r--r--. 3 root root 155288 Jul 15 08:49 core.elf
-r--r--r--. 1 root root   3368 Jul 15 08:49 configfile.mod
-r--r--r--. 1 root root   2592 Jul 15 08:49 command.lst
-r--r--r--. 1 root root  10188 Jul 15 08:49 cmp_test.mod
-r--r--r--. 1 root root   3100 Jul 15 08:49 cmp.mod
-r--r--r--. 1 root root   3864 Jul 15 08:49 cmostest.mod
-r--r--r--. 1 root root   2112 Jul 15 08:49 cmosdump.mod
-r--r--r--. 1 root root   3988 Jul 15 08:49 cmdline_cat_test.mod
-r--r--r--. 1 root root   5796 Jul 15 08:49 cbfs.mod
-r--r--r--. 1 root root   4388 Jul 15 08:49 cat.mod
-r--r--r--. 1 root root   3996 Jul 15 08:49 bufio.mod
-r--r--r--. 1 root root  54848 Jul 15 08:49 btrfs.mod
-r--r--r--. 1 root root   4544 Jul 15 08:49 bswap_test.mod
-r--r--r--. 1 root root   3780 Jul 15 08:49 boot.mod
-r--r--r--. 1 root root  22200 Jul 15 08:49 blscfg.mod
-r--r--r--. 1 root root   3784 Jul 15 08:49 blocklist.mod
-r--r--r--. 1 root root   8164 Jul 15 08:49 bitmap_scale.mod
-r--r--r--. 1 root root   4120 Jul 15 08:49 bitmap.mod
-r--r--r--. 1 root root  15956 Jul 15 08:49 bfs.mod
-r--r--r--. 1 root root   5404 Jul 15 08:49 archelp.mod
-r--r--r--. 1 root root    472 Jul 15 08:49 all_video.mod
-r--r--r--. 1 root root  14852 Jul 15 08:49 afs.mod
-r--r--r--. 1 root root  10912 Jul 15 08:49 affs.mod
-r--r--r--. 1 root root   1900 Jul 15 08:49 adler32.mod

./boot/grub/fonts:
total 2501
-r--r--r--. 1 root root 2560080 Jul 15 08:49 unicode.pf2
[root@p10-helper mnt]#

**Comment by chuckersjp** [comment]
Okay so that _looks_ like the coreos-iso-maker would definitely NOT work right out of the box.

It _might_ work with some tweaking and creative use of conditionals.

Not sure if I have the cycles for it this week.

There is also the question of whether ppc64le works with kernel parameter passing.

**Comment by vsolasa** [comment]
Thank you Chuck.. I understand, i can modify ansible playbooks but i'm not familiar on the image changes..so was looking for help.. Take your time.. next week sounds good to me.. :)

**Comment by chuckersjp** [comment]
Hrrm....this might be a bit messier than I thought.  Mainly because I don't know enough about how ppc64le ISOs are booting.  Will look at it some more later tonight maybe.

**Comment by vsolasa** [comment]
Thank you so much Chuck.. this playbook was very helpful, it resolved a bigger issue for me and it worked..

**Comment by chuckersjp** [comment]
So, the new ISO actually booted and worked?

**Comment by vsolasa** [comment]
Yes Chuck.. It did boot and it worked.

**Comment by chuckersjp** [comment]
Great!  I will do some clean up work and merge it into the main branch tomorrow if I get the time.  Thanks for the confirmation!

**Comment by vsolasa** [comment]
Sure.. i will also test it on a 5 node cluster tomorrow and let you know..

**Comment by bpradipt** [comment]
@chuckersjp few of us can also give it a try on our ppc64le lab systems. Let us know when you have the cleanups ready and we will give it a spin

@Prajyot-Parab @sudeeshjohn

**Comment by vsolasa** [comment]
@bpradipt - I tested it on a Power server from IBM Poughkeepsie.. let me know if you need any information, happy to help..

**Comment by vsolasa** [comment]
@christianh814 - how can we update the static IP installation for IBM Power on this repo? I see that you have entries for DHCP installation but not for static IP installation..

**Comment by christianh814** [comment]
@vsolasa Yup, I'll add some info when @bpradipt and @Prajyot-Parab do some tests and I have no way of verifying it.

**Comment by chuckersjp** [comment]
Changes merged into main branch:

https://github.com/chuckersjp/coreos-iso-maker

**Comment by vsolasa** [comment]
Hi Chuck, i quickly checked the playbook and when i run ansible module "setup", i notice below...probably we have to change the condition to ppc64le in the playbook.. 

"ansible_architecture": "ppc64le",

**Comment by chuckersjp** [comment]
Oh okay.  If the `setup` module spits that out, that would mean it doesn't have to be done as a user defined variable.  That is an easy fix.  I will try to get to that in a bit.  Thanks!

**Comment by chuckersjp** [comment]
Crud. no.  I forgot that `setup` doesn't actually run against the nodes because it only generates the ISOs on an Ansible control node which may or may not be a part of the cluster.

I will update the variable though for consistency sake.

**Comment by vsolasa** [comment]
@chuckersjp. Thank you for your help. 

I tested a Single node cluster and also a 5 node cluster with your Single ISO playbook. I couldn't test multi ISO but will do that as soon as possible and update the issue in here.. 

I tested on 8335 GTB Power8 KVM servers and cluster installed fine without any issues for OCP 4.5.7

**Comment by Prajyot-Parab** [comment]
@vsolasa Can you you maybe share the boot log of any your booted machine for reference purposes. Also, it would be helpful if you can share the `group_vars/all.yaml` for ppc64le specific env.
