### ISSUE TITLE
OC RSH pod-name timeout 

### ISSUE THREAD

**Issue by vtlrazin** [RedHatOfficial/ocp4-helpernode#152]
Hi,
I installed OCP cluster via ocp4-helper node with default settings.

Cluster is up and working properly.

`oc version
Client Version: 4.5.2
Server Version: 4.5.6
Kubernetes Version: v1.18.3+002a51f`

How I can increase `oc rsh pod-name`  timeout from default value **60sec**.

`oc --request-timeout 0s rsh pod-name` not increase timeout value

thanks,
Vitaliy

**Comment by christianh814** [comment]
Did you try `--pod-running-timeout`?

**Comment by vtlrazin** [comment]
Yes. PSB...

```
[root@helper ocp4]# oc rsh --pod-running-timeout=5m container bash
[root@container /]# date
Tue Sep  1 15:39:35 UTC 2020
[root@container /]# [root@helper ocp4]# 
[root@helper ocp4]# date
Tue Sep  1 18:40:59 IDT 2020

```

It cannot help.
Vitaliy

**Comment by christianh814** [comment]
There has been a timeout increase in the LB of the playbook. This is in the `devel` branch and should help this issue.

If this comes up again, please reopen.
