### ISSUE TITLE
resolver is reconfigured before named is started

### ISSUE THREAD

**Issue by dlbewley** [RedHatOfficial/ocp4-helpernode#155]
Resolv.conf is pointed to localhost
https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/tasks/main.yml#L350

...and downloading of the client
https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/tasks/main.yml#L435
is attempted before named is started.

Which is because handlers run after playbooks finish.

Modifying resolv.conf could be delayed or the handlers could be flushed prior to the downloads.

```yaml
- name: Ensure services are started before using them
  meta: flush_handlers
```

**Comment by christianh814** [comment]
Closed by #158
