### ISSUE TITLE
dhcp issue on ocp 4.5.8

### ISSUE THREAD

**Issue by levinwang88** [RedHatOfficial/ocp4-helpernode#156]
DHCP gets the IP address for the first time. After coreOS is installed and restarted, it cannot get the IP address.

here is the message. could you help to check this issue , thanks
Sep 11 18:06:53 bastion143 dhcpd: DHCPDISCOVER from c2:1c:1a:13:b1:05 via ens192: network 9.111.143.0/24: no free leases
Sep 11 18:06:54 bastion143 dhcpd: DHCPDISCOVER from 6c:ae:8b:41:3c:b2 via ens192
Sep 11 18:06:54 bastion143 dhcpd: DHCPOFFER on 9.21.58.73 to 6c:ae:8b:41:3c:b2 via ens192
Sep 11 18:06:54 bastion143 dhcpd: Dynamic and static leases present for 9.21.58.73.
Sep 11 18:06:54 bastion143 dhcpd: Remove host declaration worker3 or remove 9.21.58.73
Sep 11 18:06:54 bastion143 dhcpd: from the dynamic address pool for 9.21.58.0/24
Sep 11 18:06:54 bastion143 dhcpd: DHCPREQUEST for 9.21.58.73 (9.21.58.201) from 6c:ae:8b:41:3c:b2 via ens192
Sep 11 18:06:54 bastion143 dhcpd: DHCPACK on 9.21.58.73 to 6c:ae:8b:41:3c:b2 via ens192
Sep 11 18:06:57 bastion143 dhcpd: DHCPDISCOVER from 84:2b:2b:6f:18:cf via ens192: network 9.21.58.0/24: no free leases
Sep 11 18:07:04 bastion143 dhcpd: DHCPDISCOVER from 84:2b:2b:6f:18:cf via ens192: network 9.21.58.0 /24: no free leases

**Comment by levinwang88** [comment]
here is the /etc/dhcp/dhcpd.conf file ,you can see.
authoritative;
ddns-update-style interim;
default-lease-time 14400;
max-lease-time 14400;

        option routers                  10.10.8.2;
        option broadcast-address        10.10.8.255;
        option subnet-mask              255.255.255.0;
        option domain-name-servers      10.10.8.201;
        option domain-name              "ocp4.wmla.net";
        option domain-search            "ocp4.wmla.net", "wmla.net";

        subnet 10.10.8.0 netmask 255.255.255.0 { 
        interface ens192;
        pool {
                range 10.10.8.117 10.10.8.126;
                # Static entries
                host bootstrap { hardware ethernet 00:50:56:a1:de:8b; fixed-address 10.10.8.117; } 
                host masterw0 { hardware ethernet 00:50:56:a1:d3:7b; fixed-address 10.10.8.118; } 
                host masterw1 { hardware ethernet 00:50:56:a1:db:b0; fixed-address 10.10.8.119; } 
                host masterw2 { hardware ethernet 00:50:56:a1:15:cf; fixed-address 10.10.8.120; } 
                host workerw0 { hardware ethernet 40:f2:e9:28:bc:42; fixed-address 10.10.8.122; } 
                host workerw1 { hardware ethernet 6c:ae:8b:41:40:5a; fixed-address 10.10.8.123; } 
                host workerw2 { hardware ethernet 6c:ae:8b:41:3f:8a; fixed-address 10.10.8.124; } 
                host workerw3 { hardware ethernet 6c:ae:8b:41:3c:b2; fixed-address 10.10.8.125; } 
                host workerw4 { hardware ethernet 08:94:ef:01:12:98; fixed-address 10.10.8.126; } 
                # this will not give out addresses to hosts not listed above
                deny unknown-clients;

                # this is PXE specific
                filename "pxelinux.0";

                next-server 10.10.8.201;
        }
}

**Comment by levinwang88** [comment]
The installation of Core OS can be completed normally. After the installation is completed, the system will restart and  will can not obtained ip. thanks

**Comment by yussufsh** [comment]
@levinwang88 do you have multiple clusters/dhcp servers running on same subnet?

**Comment by christianh814** [comment]
No further information received. Closing
