### ISSUE TITLE
UEFI Booting

### ISSUE THREAD

**Issue by Etherchannel01** [RedHatOfficial/ocp4-helpernode#157]
Unfortunately my servers don't support PXE when in legacy BIOS mode. What would be the way to get the helper node setup for UEFI?

**Comment by christianh814** [comment]
@Etherchannel01 Hi, this is currently being tracked by #101 

@therevoman had suggested a solution, but work hasn't been done on it yet. If you can get it to work, we would love the PR!

**Comment by christianh814** [comment]
Should be in [devel](https://github.com/RedHatOfficial/ocp4-helpernode/pull/196) now
