### ISSUE TITLE
Remove Haproxy mode redundancy

### ISSUE THREAD

**Issue by Bilal-io** [RedHatOfficial/ocp4-helpernode#159]
Hey,

Maybe not a big deal, but perhaps Haproxy template can be cleaned up by removing redundancy

```
defaults
    mode                    http
    ...
```
Needs to be changed to `tcp` as the default, and only explicitly set `listen stats` mode to http

If my assessment is accurate, I can create a PR.

**Comment by christianh814** [comment]
> Hey,
> 
> Maybe not a big deal, but perhaps Haproxy template can be cleaned up by removing redundancy
> 
> ```
> defaults
>     mode                    http
>     ...
> ```
> 
> Needs to be changed to `tcp` as the default, and only explicitly set `listen stats` mode to http
> 
> If my assessment is accurate, I can create a PR.

I believe that's true. I think it only matters when setting up HAproxy to update it's config "dynamically"...which we aren't doing.

I'll welcome that PR! :)

**Comment by Bilal-io** [comment]
Hmm I thought the  HAProxy template was used when we run the Ansible playbook, unless you mean something different by `when setting up HAproxy to update it's config "dynamically"`

PR coming in soon

**Comment by christianh814** [comment]
Closed by #160
