### ISSUE TITLE
Not enough memory to load specified image

### ISSUE THREAD

**Issue by canit00** [RedHatOfficial/ocp4-helpernode#16]
Have been using ocp4-helpernode for quite some time, thank you! It has been a great.

Today, I needed to redeploy to an existing environment fresh since I lost access to the previous deployment artifacts.

The issue I've been running into regardless of the OS on the helpernode, I am unable to get the bootstrap node bootstrapped. The error received on the console `Not enough memory to load specified image`

Took a pcap file and there seems to be a negotiation failure with TFTP service as can be seen in the screenshot. I will rerun a fresh test and confirm. 

helpernode OS `CentOS Linux release 7.7.1908 (Core)`

![Screenshot from 2020-03-29 15-44-33](https://user-images.githubusercontent.com/17949679/77861395-5b7dc600-71da-11ea-8083-3d29b4c692da.png)
![Screenshot from 2020-03-29 15-38-20](https://user-images.githubusercontent.com/17949679/77861400-60427a00-71da-11ea-8a94-f7c6baf6a18e.png)

**Comment by christianh814** [comment]
Double check the `var.yaml` file. That "select your role" menu comes up when it can't find the right pxe boot option that matches your MAC address (see [the following task](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/tasks/main.yml#L215-L250) to see how the file is set based on mac address).

Double check that

**Comment by christianh814** [comment]
MAC address issue on the pxe server. Closing
