### ISSUE TITLE
Testing pre-release

### ISSUE THREAD

**Issue by bassplay3r** [RedHatOfficial/ocp4-helpernode#165]
Hey folks,
I'm trying to point to the pre-release version so our CI and start validating against 4.6 but I'm not sure I'm pointing to the correct URLs. I see there are files with nightly in the name and others that don't have that.  I was hoping to use the ones without nightly in the name because I assumed those would always point to the latest. Is that not the case? Am I pointing to the wrong URLs.

ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-metal4k.x86_64.raw.gz"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-live-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-live-kernel-x86_64"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest/openshift-client-linux.tar.gz"
ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest/openshift-install-linux.tar.gz"

**Comment by bassplay3r** [comment]
Friendly bump. Would be really helpful to test pre-release before we ship

**Comment by bassplay3r** [comment]
Using these URLs  
ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-4.6.0-rc.4-x86_64-metal.x86_64.raw.gz"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-4.6.0-rc.4-x86_64-live-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-4.6.0-rc.4-x86_64-live-kernel-x86_64"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest/openshift-client-linux-4.6.0-0.nightly-2020-10-03-051134.tar.gz"
ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/latest/openshift-install-linux-4.6.0-0.nightly-2020-10-03-051134.tar.gz"

I get 
![image](https://user-images.githubusercontent.com/37637605/96891834-0bf13700-1457-11eb-8df2-dba7d5aecd58.png)

**Comment by PYLochou** [comment]
It's linked to https://github.com/RedHatOfficial/ocp4-helpernode/issues/134.  New RHCOS / Fedora CoreOS now need another artifact (rootfs.)  Maintainers here are waiting for OCP 4.6 GA which is on its way (already published but channels stable-4.6 etc. are not yet updated.)

**Comment by bassplay3r** [comment]
Thanks for the update
