### ISSUE TITLE
Bootstrap ignition file is running in loop and starting with emergency mode on bootstrap server

### ISSUE THREAD

**Issue by rahulsingh45-tech** [RedHatOfficial/ocp4-helpernode#168]
Hi,

We are planning to create 3 master and 2 worker node.
We have created Service server (Helper node) with RHEL OS.
Ignition files has been created on Same server.

While running kernel command with bootstrap ignition file its running in loop and starting with emergency mode on bootstrap server .

We are unable to boot the bootstrap node .

Attached error screenshot . Please help us to resolve the issue.
![Screenshot1](https://user-images.githubusercontent.com/64540939/97834425-d9b8c280-1cfd-11eb-8656-967b7fbce5a6.jpg)

**Comment by christianh814** [comment]
In 4.5, HelperNode wasn't compatable with OKD.

I just merged a change that brings the playbook to 4.6 and it being compatible with OKD. Please pull in the latest change and try again.

**Comment by christianh814** [comment]
Please try the latest playbook and open another issue if this continues
