### ISSUE TITLE
Please add control plane nodes to ingress-http and ingress-https

### ISSUE THREAD

**Issue by gefrickel** [RedHatOfficial/ocp4-helpernode#169]
Hi everyone.
I prefer to run the upi Openshift install with the control nodes marked Scheduleable. So I could use the control plane nodes in the ingress-http and ingress-https portion of the haproxy config.
Could you please add the control plane nodes to the ingress-http and ingress-https portion of the haproxy config?
I assume that if you do not run the control plane as Schedulable there is no negative effect as the haproxy load balancer will not "balance" across the "unavailable" endpoints. So this should be a trasparent change to the existing way how it already works.
Also it would allow for "smaller" three node deployments in resource constrained environments.

Kind regards

**Comment by christianh814** [comment]
You should already be able to do this. Just omit the workers from your YAML file. [There is an example](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/examples/vars-compact.yaml) in this repo.

If you find an issue, please let us know.
