### ISSUE TITLE
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/root/ocp4-helpernode/tasks/setup_registry.yaml'

### ISSUE THREAD

**Issue by kiran-anand** [RedHatOfficial/ocp4-helpernode#171]
TASK [Mirror the registry] *******************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [Generate Local Registry information] ***************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/root/ocp4-helpernode/tasks/setup_registry.yaml': line 116, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Generate Local Registry information\n    ^ here\n"}

This seems to be an issue with tasks/setup_registry.yaml based on the configuration in vars.yaml. If the option "autosync_registry" is set to "false" in vars.yaml, one of the previous steps, “Mirror the registry”, would be skipped and would not create the required output for this step.

Possible Solution >> Edit the playbook tasks/setup_registry.yaml and add a "when:" condition for the following task "Generate Local Registry information"
Add the following line to tasks/setup_registry.yaml
  - name: Generate Local Registry information
    when: setup_registry.autosync_registry  ⇒ Add this line
    copy:
      content: "{{ registry.stdout }}"
      dest: ../postrun-local-registry-info

**Comment by christianh814** [comment]
@Prajyot-Parab PTAL

**Comment by christianh814** [comment]
Fixed by #173 and is now in `devel`
