### ISSUE TITLE
RHCOS-OCP boot is failing for worker node: ignition[xxx]: GET result: Internal Server Error

### ISSUE THREAD

**Issue by darpan91** [RedHatOfficial/ocp4-helpernode#172]
We are trying to install RHCOS-OCP. During RHCOS installation , Bootstrap & master node booted successfully. We are able to login the same.
But we are getting error while booting worker node. Please find attached error.

Openshift 4.5.2
RHCOS 4.5.2 (1 bootstrap ,3 master & 2 worker )
RHEL 7.8 (helper node)
![worker node boot error](https://user-images.githubusercontent.com/65757312/98360735-5fb37100-2050-11eb-9319-f37bd25b6e95.JPG)

**Comment by christianh814** [comment]
That's a normal error. The workers won't start until the bootstrap and masters are done installing. Only then the workers start coming up online.

If you feel there is a problem. The first place to look is in the bootstrap server. `ssh` into bootstrap server and run the `journalctl` command it tells you.

If you feel that there's an issue, please let us know.
