### ISSUE TITLE
Please allow multiple OCP4 "personalities" used for the different install methods, e.g. of 4.5 and 4.6

### ISSUE THREAD

**Issue by gefrickel** [RedHatOfficial/ocp4-helpernode#177]
Hi there,
I could not figure out on how to install ocp4-helpernode with the 4.5 "flavour". As the "latest" code seems to be 4.6.x the ocp4-helpernode installation does no longer allow for the installation of the 4.5 code.

My idea is to have both install styles supported with the ocp4-helpernode project. But I have no idea on how to do it if its already possible.

So please, how do I install 4.5 with the ocp4-helpernode? If its not possible yet / anymore I suggest to provide an option to switch the "flavour" of the installation from 4.6 (new default) to 4.5 (as it beautifully worked before).

Kind regards,
Mathias

**Comment by christianh814** [comment]
It all depends on what you supply in the `vars.yaml` file. https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/vars-doc.md#specifying-artifacts

In this case `ocp_bios` can point to the `metal-bios` or the `rootfs.img`. 4.5 wants the `metal-bios` and 4.6+ wants the `rootfs.img`

**Comment by christianh814** [comment]
@gefrickel Please see [this comment](https://github.com/RedHatOfficial/ocp4-helpernode/issues/179#issuecomment-725729622) on another issue. It shows you what to put in your `vars.yaml` file in order to install 4.5
