### ISSUE TITLE
Where do I find the dependencies for 4.5.13

### ISSUE THREAD

**Issue by bassplay3r** [RedHatOfficial/ocp4-helpernode#179]
I need to test against a specific version 4.5.13. I can find the clients but it seems only certain versions of the dependencies are available.

**Comment by christianh814** [comment]
The clients (as you already found) are hosted [here](https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.13/)

The version of RHCOS does NOT go in tandem with the Z stream of OCP. It only matches the X.Y. So there is no "4.5.13" version of RHCOS. I would recommend just downloading the "oldest" version of RHCOS and let the platform update/upgrade the version (happens during the install) to the one that is "good for" 4.5.13

Those can be found [here](https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/)

HTH!

**Comment by bassplay3r** [comment]
When you say download are you referring to something I have to do manually or just re-pointing to the older version dependencies in vars like this

ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2/rhcos-4.5.2-x86_64-metal.x86_64.raw.gz"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2/rhcos-4.5.2-x86_64-installer-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2/rhcos-4.5.2-x86_64-installer-kernel-x86_64"
ocp_client: "https://openshift-release-artifacts.svc.ci.openshift.org/4.5.13/openshift-client-linux-4.5.13.tar.gz"
ocp_installer: "https://openshift-release-artifacts.svc.ci.openshift.org/4.5.13/openshift-install-linux-4.5.13.tar.gz"
helm_source: "https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz"
release_tag: "4.5.2-x86_64"

When I did that the VMs sat and spun on this and the installed timed out. 
![image](https://user-images.githubusercontent.com/37637605/98861390-30777800-2433-11eb-80e1-dfb081237f4f.png)

**Comment by christianh814** [comment]
You just need to re-point to the older version dependencies.

What you put up there should have "just worked". I can run a test on my end.

**Comment by christianh814** [comment]
Here is your issue...you're using something that requires authentication to get

```
Nov 11 23:05:05 bootstrap.ocp4.example.com release-image-download.sh[1323]: Error: error pulling image "registry.svc.ci.openshift.org/ocp/release@
sha256:8d104847fc2371a983f7cb01c7c0a3ab35b7381d6bf7ce355d9b32a08c0031f0": unable to pull registry.svc.ci.openshift.org/ocp/release@sha256:8d104847
fc2371a983f7cb01c7c0a3ab35b7381d6bf7ce355d9b32a08c0031f0: unable to pull image: Error initializing source docker://registry.svc.ci.openshift.org/o
cp/release@sha256:8d104847fc2371a983f7cb01c7c0a3ab35b7381d6bf7ce355d9b32a08c0031f0: Error reading manifest sha256:8d104847fc2371a983f7cb01c7c0a3ab
35b7381d6bf7ce355d9b32a08c0031f0 in registry.svc.ci.openshift.org/ocp/release: unauthorized: authentication required
```

I was able to install 4.5 with no problem using the following in my `vars.yaml` file

```
ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2/rhcos-4.5.2-x86_64-metal.x86_64.raw.gz"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2/rhcos-4.5.2-x86_64-installer-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2/rhcos-4.5.2-x86_64-installer-kernel-x86_64"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.13/openshift-client-linux-4.5.13.tar.gz"
ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.13/openshift-install-linux-4.5.13.tar.gz"
helm_source: "https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz"
```

HTH!

**Comment by bassplay3r** [comment]
Your settings worked great. Thank you so much!
