### ISSUE TITLE
single master possible?

### ISSUE THREAD

**Issue by shaof777** [RedHatOfficial/ocp4-helpernode#194]
Following [this quickstart](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/quickstart.md), try to install a single master configuration in a virsh environment, but looks like failed. How to troubleshoot?

ps: also tried to install a 3 masters cluster using this quickstart, succeed.

**Comment by christianh814** [comment]
Single master isn't supported. You can try setting...

```
oc patch etcd cluster -p='{"spec": {"unsupportedConfigOverrides": {"useUnsupportedUnsafeNonHANonProductionUnstableEtcd": true}}}' --type=merge
```

During bootstrapping to get a single master.

If you're interested in a "Single Node Cluster"; you can try out the SNC project https://github.com/code-ready/snc
