### ISSUE TITLE
/usr/local/bin not in root's path

### ISSUE THREAD

**Issue by langdon** [RedHatOfficial/ocp4-helpernode#202]
in:

> Next, install the helpernodectl CLI utility binary and put it somehwere in your $PATH, in my example I'm installing it in /usr/local/bin
> 
> curl -LO https://github.com/RedHatOfficial/ocp4-helpernode/releases/download/v2alpha1/helpernodectl
> mv helpernodectl /usr/local/bin/
> chmod +x /usr/local/bin/helpernodectl

You suggest using `/usr/local/bin` for the ctl app. However, root's default path is `PATH=/sbin:/bin:/usr/sbin:/usr/bin`. I would recommend making the content suggest /usr/bin or some such just to minimize issues.

**Comment by christianh814** [comment]
I may just add an `export` command

**Comment by christianh814** [comment]
Closed by [this commit](https://github.com/RedHatOfficial/ocp4-helpernode/blob/ab4f1fad2c5b923ec39459e58d51d1b40842ad34/mkdocs/docs/fullstack-quickstart.md) and is now live on https://redhatofficial.github.io/ocp4-helpernode/fullstack-quickstart/
