### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by vsolasa** [RedHatOfficial/ocp4-helpernode#217]
Hi Team,

Could you please update the ReadMe to the below syntax? 

https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/quickstart-powervm.md#install-rhcos-to-all-lpars

Documentation is confusing.

Existing command - 
lpar_netboot -f -t ent -m -s auto -d auto <lpar_name> <profile_name> <managed_system>

New - 
lpar_netboot -f -t ent -m (mac address) -s auto -d auto <lpar_name> <profile_name> <managed_system>

Regards
Veera Solasa.

**Comment by christianh814** [comment]
This is updated on devel

https://github.com/RedHatOfficial/ocp4-helpernode/blob/devel/docs/quickstart-powervm.md#install-rhcos-to-all-lpars
