### ISSUE TITLE
Support external LB and DNS for install

### ISSUE THREAD

**Issue by cs-zhang** [RedHatOfficial/ocp4-helpernode#218]
This feature requires following conditions:
1. Predefined IPs for all OCP nodes
2. Predefined cluster domain name and cluster ID
3. Load balancer is pre-configured with static IPs for the OCP cluster
4. DNS is pre-configured with above info
5. No external DHCP 

In this case, the DNS and LB(haproxy) on helpernode will not be used for OCP installation.

**Comment by christianh814** [comment]
Merged into Devel
