### ISSUE TITLE
Make OCP and Helm versions variables 

### ISSUE THREAD

**Issue by kjw3** [RedHatOfficial/ocp4-helpernode#229]
In vars/main.yml the OCP version is hardcoded and same with helm version. It would be nice if these were variables so that you could try different versions with an easier change.

`ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live-rootfs.x86_64.img"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live-kernel-x86_64"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.12/openshift-client-linux-4.6.12.tar.gz"
ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.12/openshift-install-linux-4.6.12.tar.gz"
helm_source: "https://get.helm.sh/helm-v3.5.0-linux-amd64.tar.gz"`

**Comment by christianh814** [comment]
You can change that to point to any get helm URL to use.
