### ISSUE TITLE
Questions: Helper node and DHCP variables in the helpernode.yaml

### ISSUE THREAD

**Issue by steve-delillo** [RedHatOfficial/ocp4-helpernode#230]
I am currently building an infrastructure node (helper node) where only the helper node will have access to the internet.  The helper node will also have a private IP to communicate with the other cluster components, like the Masters and Workers.

My questions about the variables in the Helper section are as follows for my particular setup:

helper:
  name: "helper"                            ===> **Can I name this the same as the public network name of my helper node.  I am concerned that calling it "helper" will cause a conflict with the actual hostname.**
  ipaddr: "192.168.7.77"                 ===> **Is this supposed to be the public IP of the helper node, or the private IP that is communicating with the other cluster components?**
  

With regards to the DHCP server section, I will need to use all private IPs, as I cannot connect this DHCP server to our public intranet for security reasons.  **So, are the IPs that are shown in the following example private IPs?**

<img width="479" alt="image" src="https://user-images.githubusercontent.com/84864338/124000574-94ca5600-d988-11eb-8090-92e3b64ba4a5.png">

**Comment by christianh814** [comment]
@steve-delillo Answers inline

> I am currently building an infrastructure node (helper node) where only the helper node will have access to the internet. The helper node will also have a private IP to communicate with the other cluster components, like the Masters and Workers.
> 
> My questions about the variables in the Helper section are as follows for my particular setup:
> 
> helper:
> name: "helper" ===> **Can I name this the same as the public network name of my helper node. I am concerned that calling it "helper" will cause a conflict with the actual hostname.**

You can name this whatever you'd like. The caveat being is that the name will be used when the DNS server is set up.

> ipaddr: "192.168.7.77" ===> **Is this supposed to be the public IP of the helper node, or the private IP that is communicating with the other cluster components?**

This is supposed to be the IP address of the ip address used to communicate with other cluster components.

> 
> With regards to the DHCP server section, I will need to use all private IPs, as I cannot connect this DHCP server to our public intranet for security reasons. **So, are the IPs that are shown in the following example private IPs?**
> 
> <img alt="image" width="479" src="https://user-images.githubusercontent.com/84864338/124000574-94ca5600-d988-11eb-8090-92e3b64ba4a5.png">

These are the IP ranges used to set up the DHCP server on the helpernode. This section is optional, but that means that you'll have to set up your cluster with static IPs.

HTH

**Comment by steve-delillo** [comment]
Great.  Thank you for that information, Christian.
