### ISSUE TITLE
Using the Full Stack quickstart (v2), do the RHCOS images go into a specific path?

### ISSUE THREAD

**Issue by steve-delillo** [RedHatOfficial/ocp4-helpernode#231]
Went through the entire install process in the following link: https://redhatofficial.github.io/ocp4-helpernode/fullstack-quickstart/  (the Full Stack quickstart)

For the setup shown above, is there a specific path where we should download the RHCOS kernel, initramfs, rootfs, etc. on the helper node so we can PXE boot to these images?  I didn't see anywhere in that link where the RHCOS images were downloaded, so I assume that we do this ourselves.

**Comment by christianh814** [comment]
@steve-delillo The RHCOS kernel, initramfs, etc are "prebuilt" into the container. So you don't have to download them yourself.
