### ISSUE TITLE
ocp4helper v2 cannot execute binary file: Exec format error on ppc64 linux

### ISSUE THREAD

**Issue by mingkui** [RedHatOfficial/ocp4-helpernode#233]
[root@ocp4helper2 data]# which helpernodectl
/usr/local/bin/helpernodectl

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[root@ocp4helper2 data]# helpernodectl completion bash
-bash: /usr/local/bin/helpernodectl: cannot execute binary file: Exec format error

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[root@ocp4helper2 data]# uname -a
Linux ocp4helper2.ocp47.lbs.local 4.18.0-240.el8.ppc64le #1 SMP Fri Sep 25 19:50:23 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux

**Comment by christianh814** [comment]
Unfortunately PPC64 arch isn't supported for v2 at the moment
