### ISSUE TITLE
Error installing 4.7

### ISSUE THREAD

**Issue by kumaravel2** [RedHatOfficial/ocp4-helpernode#234]
Seems the installation is looking for live.rootfs, 

Displaying logs from failed units: sysroot.mount
coreos-livepxe-rootfs.service
-- Logs begin at Wed 2021-07-07 18:28:29 UTC, end at Wed 2021-07-07 18:28:33 UTC. --
Jul 07 18:28:33 systemd[1]: Mounting /sysroot...
Jul 07 18:28:33 mount[817]: mount: /sysroot: failed to setup loop device for /root.squashfs.
Jul 07 18:28:33 systemd[1]: sysroot.mount: Mount process exited, code=exited status=32
Jul 07 18:28:33 systemd[1]: sysroot.mount: Failed with result 'exit-code'.
Jul 07 18:28:33 systemd[1]: Failed to mount /sysroot.
-- Logs begin at Wed 2021-07-07 18:28:29 UTC, end at Wed 2021-07-07 18:28:33 UTC. --
Jul 07 18:28:33 systemd[1]: Starting Acquire live PXE rootfs image...
Jul 07 18:28:33 coreos-livepxe-rootfs[798]: No rootfs image found.  Modify your PXE configuration to add the rootfs
Jul 07 18:28:33 coreos-livepxe-rootfs[798]: image as a second initrd, or use the coreos.live.rootfs_url= kernel parameter
Jul 07 18:28:33 coreos-livepxe-rootfs[798]: to specify an HTTP or HTTPS URL to the rootfs.
Jul 07 18:28:33 systemd[1]: coreos-livepxe-rootfs.service: Main process exited, code=exited, status=1/FAILURE
Jul 07 18:28:33 systemd[1]: coreos-livepxe-rootfs.service: Failed with result 'exit-code'.
Jul 07 18:28:33 systemd[1]: Failed to start Acquire live PXE rootfs image.
Jul 07 18:28:33 systemd[1]: coreos-livepxe-rootfs.service: Triggering OnFailure= dependencies.

+++++++++++++++++++++
[   13.338873] coreos-installer-service[1265]: Failed to fetch signature: fetching signature URL
[   13.350278] coreos-installer-service[1265]: Error: --insecure not specified and signature not found
[FAILED] Failed to start CoreOS Installer.
See 'systemctl status coreos-installer.service' for details.

**Comment by christianh814** [comment]
Interesting, looks like the name changed again. I was going to push a change to master but I'll do some testing for 4.7 in devel and see if I can't make a change there.

**Comment by christianh814** [comment]
This should be fixed in the latest release
