### ISSUE TITLE
Setting the IP of the bootstrap node in the grub kernel parameters fails to create a network config file

### ISSUE THREAD

**Issue by steve-delillo** [RedHatOfficial/ocp4-helpernode#235]
Here, I am network booting the bootstrap node to load RHCOS.  I failed to get a good load and see the following error after RHCOS gets loaded and the bootstrap comes up to its login prompt.
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/84864338/125135878-98fc1f00-e0be-11eb-9528-7493c03899fb.png">

Also, the haproxy status screen shows that the bootstrap did not complete successfully:
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/84864338/125136599-00ff3500-e0c0-11eb-8a01-20b753113289.png">

Spoke with some folks who have done OCP cluster installs and they mentioned having to use the filetranspiler to inject network configuration files.  However, I looked into the documentation and saw that this may not be needed anymore.  In the following section of the vars.yaml documentation, it states that if we set ip=...  the IP should get set on the server that you are loading.  Although the IP does get set, we do not get an ifcfg file on the bootstrap node in /etc/sysconfig/network-scripts.  As a matter of fact, all ifcfg-* files get deleted, completely, which was really unexpected.

From the vars.yaml documentation.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/84864338/125136059-e9737c80-e0be-11eb-8f5d-44d79fb47e18.png">

Here you can see that after RHCOS loads on the bootstrap server, no network config files exist, at all:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/84864338/125136340-80d8cf80-e0bf-11eb-91a9-8c5f3b5c7f08.png">

Here, you can see where I set the IP like the docs tell us to do.  If we don't want to have to do the whole, complicated process of doing the filetranspiler, are there other parameters other than "ip" that we should add into the kernel parameters: prefix, domain, DNS, etc.?
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/84864338/125136168-20e22900-e0bf-11eb-85e5-c13e358016ad.png">

**Comment by christianh814** [comment]
The syntax can be found here

https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/bmquickstart-static.md#install-instances
Example

```
ip=192.168.7.20::192.168.7.1:255.255.255.0:bootstrap.ocp4.example.com:enp1s0:none
nameserver=192.168.7.77
```

It's a bit much, but it's basically

```
ip=<ipaddress>::<defaultgw>:<netmask>:<hostname>:<iface>:none
```

More info can be found here: https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-user-infra-machines-static-network_installing-bare-metal-network-customizations

**Comment by steve-delillo** [comment]
Nice.  Thank you, @christianh814 .  I didn't see that link.  Will give that a try.

**Comment by steve-delillo** [comment]
Looks like we are getting further along.  Looks like putting the following in our grub file made it possible to set the network config on our bootstrap server

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/84864338/125213565-8c66fa80-e267-11eb-8ff5-a4874ef0582a.png">

However, even though our bootstrap server seems to be loading and comes to the "bootstrap login" prompt, the haproxy still shows the bootstrap as red.  Do we need to have the bootstrap go green (status UP) before moving on to the the Master nodes?

<img width="1667" alt="image" src="https://user-images.githubusercontent.com/84864338/125213632-e4056600-e267-11eb-9c54-45da46044b2f.png">

Also, when we try to ssh into the boostrap, we have to use the IP address.  Neither the network name nor the FQDN of the boostrap allows us to ssh.

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/84864338/125213686-2d55b580-e268-11eb-9a28-2dd9ec699047.png">


We get the following from the journalctl of the bootstrap:

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/84864338/125213701-40688580-e268-11eb-9895-d01216b7f325.png">

**Comment by steve-delillo** [comment]
I had also performed the following on the helper node so the servers on the private network could talk out to the internet.
ens3f0 is the adapter that accesses the public.


INTERFACE_NAME=ens3f0
if [[ ! -z ${1} ]]; then
    INTERFACE_NAME=${1}
    echo "==> Using $INTERFACE_NAME passed into script..."
fi

/sbin/iptables --flush
/sbin/iptables --table nat --flush
/sbin/iptables --delete-chain
/sbin/iptables --table nat --delete-chain
/sbin/iptables --table nat --append POSTROUTING --out-interface $INTERFACE_NAME -j MASQUERADE
/sbin/iptables --append FORWARD --in-interface $INTERFACE_NAME -j ACCEPT

echo 1 > /proc/sys/net/ipv4/ip_forward

**Comment by christianh814** [comment]
Can you rebase? There was some DNS changes that might help here https://github.com/RedHatOfficial/ocp4-helpernode/pull/236

**Comment by christianh814** [comment]
> I had also performed the following on the helper node so the servers on the private network could talk out to the internet.
> ens3f0 is the adapter that accesses the public.
> 
> INTERFACE_NAME=ens3f0
> if [[ ! -z ${1} ]]; then
> INTERFACE_NAME=${1}
> echo "==> Using $INTERFACE_NAME passed into script..."
> fi
> 
> /sbin/iptables --flush
> /sbin/iptables --table nat --flush
> /sbin/iptables --delete-chain
> /sbin/iptables --table nat --delete-chain
> /sbin/iptables --table nat --append POSTROUTING --out-interface $INTERFACE_NAME -j MASQUERADE
> /sbin/iptables --append FORWARD --in-interface $INTERFACE_NAME -j ACCEPT
> 
> echo 1 > /proc/sys/net/ipv4/ip_forward

You might also have to set `net.ipv4.conf.default.forwarding=1`

**Comment by steve-delillo** [comment]
"You might also have to set net.ipv4.conf.default.forwarding=1"

That had the default value of "1", already.
<img width="849" alt="image" src="https://user-images.githubusercontent.com/84864338/125330743-f92bd480-e2fb-11eb-8142-acbce1c29cf0.png">

**Comment by steve-delillo** [comment]
After rebasing (July 12), still seeing the same issue.  Again, we are coming to the bootstrap login, but haproxy screen is still showing status as "red". Here is the vars.yaml that we are using and the entries in the grub file for the bootstrap node.  Can you confirm that everything looks OK for what we are doing?  This is for bare-metal servers where only the helper node has access to the the internet (public access).  Maybe we are just missing something simple.  If everything looks good, will just attempt to make the ifcfg files via the filetranspiler - although that is very laborious.

bootstrap's IP to be: 192.168.7.20
helper node IP:          192.168.7.77


# **cat vars.yaml** 
---
disk: sda
helper:
  name: "hpo-infra1"
  ipaddr: "192.168.7.77"
  networkifacename: "ens3f3"
dns:
  domain: "example.com"
  clusterid: "ocp4"
  forwarder1: "9.11.227.25"          ==> This is a lab DNS
  forwarder2: "9.0.128.50"          ==> This is a lab DNS.
dhcp:
  router: "192.168.7.1"
  bcast: "192.168.7.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.7.10"
  poolend: "192.168.7.30"
  ipid: "192.168.7.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.7.20"
  macaddr: "bc:97:e1:86:0a:6c"
masters:
  - name: "master0"
    ipaddr: "192.168.7.21"
    macaddr: "bc:97:e1:86:0a:5c"
  - name: "master1"
    ipaddr: "192.168.7.22"
    macaddr: "bc:97:e1:86:02:ec"
  - name: "master2"
    ipaddr: "192.168.7.23"
    macaddr: "bc:97:e1:86:02:e4"
pxe:
  generate_default: true
uefi: true
install_filetranspiler: true
ocp_bios: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-4.8.0-rc.3-x86_64-live-rootfs.x86_64.img"
ocp_initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-4.8.0-rc.3-x86_64-live-initramfs.x86_64.img"
ocp_install_kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-4.8.0-rc.3-x86_64-live-kernel-x86_64"
ocp_client: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/latest/openshift-client-linux-4.9.0-0.nightly-2021-07-12-095728.tar.gz"
ocp_installer: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/latest/openshift-install-linux-4.9.0-0.nightly-2021-07-12-095728.tar.gz"


# **cat /var/lib/tftpboot/grub2/grub.cfg-01-bc-97-e1-86-0a-6c**
  
set default=0
set timeout=10

menuentry 'Install Bootstrap Node' {
  linuxefi rhcos/kernel initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=192.168.7.20::192.168.7.1:255.255.255.0:bootstrap.ocp4.example.com:ens7f0:none nameserver=192.168.7.77 coreos.inst=yes coreos.inst.install_dev=sda  coreos.live.rootfs_url=http://192.168.7.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/bootstrap.ign
  initrdefi rhcos/initramfs.img
}


Finally, rebuilt the ignition files before network booting the bootstrap server.

**Comment by christianh814** [comment]
> only the helper node has access to the the internet

This is the issue. The bootstrap will try and reach out to the internet to do the install. The Helpernode isn't set up to be a router (Although you can try to set it up that way), but that's beyond the scope of this playbook.

 It might be easier/better to do a [disconnected install](https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-restricted-networks-bare-metal.html)

**Comment by steve-delillo** [comment]
Thank you, Christian.  Actually, figured out that it was my infrastructure node's firewall settings.  The playbook opened quite a few of the ports, but it must have not gotten all of them.  Seems that there were some other ports that needed to allow traffic, although I never figured out exactly which ones.  Instead, I temporarily stopped my firewall.service and the bootstrap was able to pull what it needed from the external sites.  Just restarted the firewall after the bootstrap and masters were installed.
