### ISSUE TITLE
installer issue 

### ISSUE THREAD

**Issue by kumaravel2** [RedHatOfficial/ocp4-helpernode#238]
[root@helper]# openshift-install wait-for bootstrap-complete --log-level debug
DEBUG OpenShift Installer 4.8.0                    
DEBUG Built from commit a5ddd2dd6c72d8a5ea0a5f17acd8b964b6a3d1be 
INFO Waiting up to 20m0s for the Kubernetes API at https://api.ocp4.example.com:6443... 
DEBUG Still waiting for the Kubernetes API: an error on the server ("") has prevented the request from succeeding 

Most of the time the installer through this error, how can I proceed to debug this issue or any know issues?

**Comment by christianh814** [comment]
I would export the KUBECONFIG and run some `oc` commands to see if anything is up and running. I would also SSH into the bootstrap node and check the logs.

**Comment by auguysha** [comment]
I've been having the same issue with UIP install on vSphere. Any solution yet?

**Comment by kumaravel2** [comment]
the actual issue was due to the grub config, i used coreos.live.rootfs_url and it's image. Now the issue is resolved.

**Comment by christianh814** [comment]
Glad the issue is fixed. Although You shouldn't have to be changing any of the configs. Sounds like you provided a wrongly configured `vars.yaml`
