### ISSUE TITLE
RFE: Network Interface should be dynamic, unless set

### ISSUE THREAD

**Issue by christianh814** [RedHatOfficial/ocp4-helpernode#27]
Right now, a user must set the interface name under `helper.networkifacename` when setting up the [vars.yaml](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/examples/vars.yaml#L6) file.

I propose we set this to the default interface provided by ansible using `{{ ansible_default_ipv4.interface }}`

Although I think we should have a mechanism to let the user override this. It should go...

- The playbook will use `{{ ansible_default_ipv4.interface }}` if `helper.networkifacename` is not provided
- The playbook will use `helper.networkifacename` if provided, overriding `{{ ansible_default_ipv4.interface }}`

**Comment by niteshnarayanlal** [comment]
Hi,
For helper.networkifacename, do we have to provide the interface that is connected to the external network?
Although on doing that, the 'ansible-playbook -e @vars.yaml tasks/main.yml' fails while downloading the packages:
TASK [Downloading OCP4 installer Bios] **************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/var/www/html/install/bios.raw.gz", "elapsed": 10, "gid": 0, "group": "root", "mode": "0555", "msg": "Request failed: <urlopen error [Errno -2] Name or service not known>", "owner": "root", "secontext": "system_u:object_r:httpd_sys_content_t:s0", "size": 175505408, "state": "file", "uid": 0, "url": "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/4.3.0/rhcos-4.3.0-x86_64-metal.raw.gz"}

**Comment by christianh814** [comment]
> For helper.networkifacename, do we have to provide the interface that is connected to the external network?

Yes. The playbook requires a connection to the internet.

**Comment by niteshnarayanlal** [comment]
Thanks for the response.

I tried doing that,  but the script was still not able to download the required files.
Here is a sequence that happens:
1. Reboot and once the console is up, try wget and it works out fine.
2. Run the ansible-playbook command and provide it with an interface that is connected to the external network.
3. wget fails from the script and without the script as well.
Most probably it is modifying the network in some manner.

Also, for the PXE boot to work, I am assuming the machines need to be connected to the public network via one interface and a private network with another interface. These interfaces that are connected to the private network are going to configured with the DHCP server. Is that correct?

**Comment by canit00** [comment]
@niteshnarayanlal can you please raise a separate issue? This RFE is meant to track work for the project.

**Comment by christianh814** [comment]
This is now in `devel`. Closing via #33
