### ISSUE TITLE
Autoboot for coreos nodes

### ISSUE THREAD

**Issue by bassplay3r** [RedHatOfficial/ocp4-helpernode#36]
I could not find your devel repo here is a minor suggestion to your quickstart.  I don't have to manually choose pxe. 

Author: David Bellizzi <bassplay3r@gmail.com>
Date:   Tue Apr 14 10:39:45 2020 -0400

    Remove manaual boot step from quickstart

diff --git a/docs/quickstart.md b/docs/quickstart.md
index 5f4c6e0..4fc2171 100644
--- a/docs/quickstart.md
+++ b/docs/quickstart.md
@@ -61,7 +61,7 @@ __EL 7__
 virt-install --name="ocp4-aHelper" --vcpus=2 --ram=4096 \
 --disk path=/var/lib/libvirt/images/ocp4-aHelper.qcow2,bus=virtio,size=30 \
 --os-variant centos7.0 --network network=openshift4,model=virtio \
---boot menu=on --location /var/lib/libvirt/ISO/CentOS-7-x86_64-Minimal-1810.iso \
+--boot hd,network,menu=on --location /var/lib/libvirt/ISO/CentOS-7-x86_64-Minimal-1810.iso \
 --initrd-inject helper-ks.cfg --extra-args "inst.ks=file:/helper-ks.cfg" --noautoconsole
 ```

@@ -70,7 +70,7 @@ __EL 8__
 virt-install --name="ocp4-aHelper" --vcpus=2 --ram=4096 \
 --disk path=/var/lib/libvirt/images/ocp4-aHelper.qcow2,bus=virtio,size=50 \
 --os-variant centos8 --network network=openshift4,model=virtio \
---boot menu=on --location /var/lib/libvirt/ISO/CentOS-8-x86_64-1905-dvd1.iso \
+--boot hd,network,menu=on --location /var/lib/libvirt/ISO/CentOS-8-x86_64-1905-dvd1.iso \
 --initrd-inject helper-ks.cfg --extra-args "inst.ks=file:/helper-ks.cfg" --noautoconsole
 ```

@@ -194,7 +194,7 @@ mkdir ~/ocp4
 cd ~/ocp4
 ```

-Create a place to store your pull-secret
+Create a place to store your pull-secret

 ```
 mkdir -p ~/.openshift
@@ -290,7 +290,7 @@ chmod o+r /var/www/html/ignition/*.ign

 ## Install VMs

-Launch `virt-manager`, and boot the VMs into the boot menu; and select PXE. The vms should boot into the proper PXE profile, based on their IP address.
+Launch `virt-manager`, and boot the VMs. The vms should boot into the proper PXE profile, based on their IP address.

 Boot/install the VMs in the following order

**Comment by christianh814** [comment]
You can find the `devel` branch [here](https://github.com/RedHatOfficial/ocp4-helpernode/tree/devel)

But I'm pulling in some changes to the devel branch this week and I can make these changes :)

**Comment by bassplay3r** [comment]
Thanks! You might want to change this to branch. :D

`To contribue please checkout/fork the devel repo and PR against that repo. `

**Comment by christianh814** [comment]
> Thanks! You might want to change this to branch. :D
> 
> `To contribue please checkout/fork the devel repo and PR against that repo. `

Updated the doc with commit b319848f72df32ef020e1bd3ea67f99046ac1751
