### ISSUE TITLE
Helper name resolution config always adds FQDN

### ISSUE THREAD

**Issue by bassplay3r** [RedHatOfficial/ocp4-helpernode#38]
To use ocp4_helpernode in my CI I had to multihome the helper by adding another interface in the kickstart file and then specify eth1 in the vars.  

```
network  --bootproto=static --device=eth0 --gateway= 1.2.3.1 --ip=1.2.3.4 --nameserver=5.6.7.8 --netmask=255.255.252.0 --ipv6=auto --activate
network  --bootproto=static --device=eth1 --gateway=NETWORK.1 --ip=NETWORK.77 --nameserver=5.6.7.8 --netmask=255.255.255.0 --ipv6=auto --activate
```

Note: NETWORK is replaced by the CI

All that works great but I found I had to go in after I ran your ansible and set the resolver config to 

```
[root@helper ~]# cat /etc/resolv.conf
search ci3dmymdepagxtz.foo.bar.com
nameserver 127.0.0.1
nameserver 5.6.7.8
[root@helper ~]#
```

When on the helper and I try to ssh -i ~/.ssh/key <ip address of worker> it says 

ssh: Could not resolve hostname <ip address of worker>.ci3dmymdepagxtz.foo.bar.com: Name or service not known

But if I just use worker0 it works,

**Comment by canit00** [comment]
Hi David -

Being able to ssh to any node in the cluster is logically done for user convenience & also taking into account that users may be working in environments with multiple domains, etc..

That being said, the code snippet creates an ssh key pair specifically for the cluster which configures your $HOME/.ssh/config with the FQDN provided in the vars.yaml file along with the core user as it's default in RHCOS.

https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/tasks/generate_ssh_keys.yaml#L1-L23

Sorry if this caused confusion.

**Comment by bassplay3r** [comment]
But I provided my public key in the install-config.yaml and the helper_rsa is not my private key
Did I miss a step?
I don't mind telling my users to do ssh worker0 if the key works 

```
[root@helper ~]# ssh worker0
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
[root@helper ~]#

```

It works when I do ssh -i mykey core@worker0

**Comment by christianh814** [comment]
> But I provided my public key in the install-config.yaml and the helper_rsa is not my private key
> Did I miss a step?
> I don't mind telling my users to do ssh worker0 if the key works
> 
> ```
> [root@helper ~]# ssh worker0
> Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
> [root@helper ~]#
> ```
> 
> It works when I do ssh -i mykey core@worker0

Look in `~/.ssh/config` and all will be answered.

As @canit00 eluded, it defaults to use the key it auto generates https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/tasks/generate_ssh_keys.yaml#L1-L23

If you look at the [vars doc](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/vars-doc.md#ssh-key) you'll see you can turn off creating an ssh-key by setting `ssh_gen_key: false` in your `vars.yaml` file.

**Comment by bassplay3r** [comment]
Thanks for extra info, it's been a long day. I'll probably have to disable the feature. I looked on the worker and all of the authorized_keys files match the public key I provided. I tried renaming my private key file helper_rsa and giving it the same perms and that does not work. 

You might want to add some more info after this line in the quickstart for those providing their own key to disable the keygen:
`This playbook creates an sshkey for you; it's under ~/.ssh/helper_rsa. You can use this key or create/user another one if you wish.`

**Comment by christianh814** [comment]
> Thanks for extra info, it's been a long day. I'll probably have to disable the feature. I looked on the worker and all of the authorized_keys files match the public key I provided. I tried renaming my private key file helper_rsa and giving it the same perms and that does not work.
> 
> You might want to add some more info after this line in the quickstart for those providing their own key to disable the keygen:
> `This playbook creates an sshkey for you; it's under ~/.ssh/helper_rsa. You can use this key or create/user another one if you wish.`

Good idea. Added a note on commit 1058934c4319602d31fda65d2911da3e4b5d0e6e

This will make it's way into master next release (sometime next week)
