### ISSUE TITLE
OCP4 failed to pull image from private registry x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by rllzyy** [RedHatOfficial/ocp4-helpernode#39]
I just created a private registry, and want to pull image from it. could anyone help please? thx a lot
Steps:
on MISC machine 
1.openssl req -newkey rsa:4096 -nodes -sha256 -keyout domain.key  -x509 -days 3650 -out domain.crt -subj "/C=CN/ST=GD/L=SZ/O=Global Security/OU=IT Department/CN=*.xxxxx.com"
2.cp /etc/crts/domain.crt /etc/pki/ca-trust/source/anchors/
3.update-ca-trust extract
4.mkdir -p /data/registry
5.cat << EOF > /etc/docker-distribution/registry/config.yml
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /data/registry
    delete:
        enabled: true
http:
    addr: :8443
    tls:
       certificate: /etc/crts/domain.crt
       key: /etc/crts/domain.key
EOF
6.systemctl restart docker
7.systemctl enable docker-distribution
8.systemctl restart docker-distribution
9.add 127.0.0.1 registry.xxxxx.com:8443 to /etc/hosts
10.docker login registry.xxxxxx.com:8443 -u root -p xxxxxx
11.podman login registry.xxxxxxx.com:8443 -u root -p xxxxx
12.docker pull nginx:latest
13.docker tag xxxx(imageID) registry.xxxxxx.com:8443/nginx:latest
14.docker push registry.xxxxxx.com:8443/nginx:latest
15.make nginx.yaml as
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deploymentoc secrets link default mindsphere-secret --for=pull
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.xxxxxx.com:8443/nginx:latest
        #image: nginx:latest
        ports:
        - containerPort: 80
      serviceAccount: default
      serviceAccountName: default
16.oc create secret generic reg-secret --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson
17.oc secrets link default reg-secret --for=pull
18.ssh core@worker0  and add MISC IP with registry.xxxxxx.com  //all nodes
19.oc apply -f nginx.yaml

Result:
Failed to pull image "registry.xxxxxx.com:8443/nginx:latest": rpc error: code = Unknown desc = error pinging docker registry registry.xxxxxx.com:8443: Get https://registry.xxxxxx.com:8443/v2/: x509: certificate signed by unknown authority

**Comment by christianh814** [comment]
You need to add this custom certificate to your cluster

https://docs.openshift.com/container-platform/4.3/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki

Closing as this is not a helpernode issue.
