### ISSUE TITLE
Master node fails to come up due to SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by niteshnarayanlal** [RedHatOfficial/ocp4-helpernode#50]
Hi,
I am trying a UPI deployment with a mix of VMs (bootstrap and master) and bare metals (workers).
All of the VMs and the bare metal are on the same network, however, only the helper node and worker nodes have an additional interface with direct access to the external network.

So far, my bootstrap node is coming out just fine, however, when I try to bring up the master node after installation it hangs with the following console logs:

[   35.681457] systemd[1]: Starting dracut pre-mount hook...
         Starting dracut pre-mount hook...
[   35.698322] systemd[1]: Started dracut pre-mount hook.
[  OK  ] Started dracut pre-mount hook.
[   36.785229] ignition[706]: GET https://api-int.ocp4.example.com:22623/config/master: attempt #11
[   36.789469] ignition[706]: GET error: Get https://api-int.ocp4.example.com:22623/config/master: EOF
[ ***  ] A start job is running for Ignition (fetch) (38s / no limit)[   41.790268] ignition[706]: GET https://api-int.ocp4.example.com:22623/config/master: attempt #12
[   41.794543] ignition[706]: GET error: Get https://api-int.ocp4.example.com:22623/config/master: EOF
[**    ] A start job is running for Ignition (fetch) (43s / no limit)[   46.795065] ignition[706]: GET https://api-int.ocp4.example.com:22623/config/master: attempt #13
[   46.799328] ignition[706]: GET error: Get https://api-int.ocp4.example.com:22623/config/master: EOF
[   ***] A start job is running for Ignition (fetch) (48s / no limit)[   51.800174] ignition[706]: GET https://api-int.ocp4.example.com:22623/config/master: attempt #14
[   51.804033] ignition[706]: GET error: Get https://api-int.ocp4.example.com:22623/config/master: EOF
[   ***] A start job is running for Ignition (fetch) (53s / no limit)[   56.804746] ignition[706]: GET https://api-int.ocp4.example.com:22623/config/master: attempt #15
[   56.810427] ignition[706]: GET error: Get https://api-int.ocp4.example.com:22623/config/master: EOF
[**    ] A start job is running for Ignition (fetch) (58s / no limit)[   61.806363] ignition[706]: GET https://api-int.ocp4.example.com:22623/config/master: attempt #16
[   61.810235] ignition[706]: GET error: Get https://api-int.ocp4.example.com:22623/config/master: EOF

On the helper node, I tried making the same request as that of the master node:
[root@helper ocp4]# curl -vk https://api-int.ocp4.example.com:22623/
*   Trying 192.168.67.130...
* TCP_NODELAY set
* Connected to api-int.ocp4.example.com (192.168.67.130) port 22623 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api-int.ocp4.example.com:22623 
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api-int.ocp4.example.com:22623 

The bootstrap didn't capture anything in its log:
[core@bootstrap ~]$ journalctl -b -f -u bootkube.service
-- Logs begin at Wed 2020-05-06 17:33:42 UTC. --

Any suggestions on what is causing this issue.

**Comment by christianh814** [comment]
```
[ 56.810427] ignition[706]: GET error: Get https://api-int.ocp4.example.com:22623/config/master: EOF
[ ] A sta
```

means that the machineconfig server didn't come up on the bootstrap. Try and debug why with

```
systemctl start bootkube
```

On the bootstrap then check the logs

**Comment by christianh814** [comment]
There has been 3 releases since this issue has filed. Please try the latest release and open another issue if you run into this problem again.
