### ISSUE TITLE
how to set ocp node hostname?

### ISSUE THREAD

**Issue by ragpo** [RedHatOfficial/ocp4-helpernode#6]
how to set ocp node hostname? by dhcp-server?  I add a new node, and add new one dhcp line, but the hostname is default localhost.

`/etc/dhcp/dhcpd.conf

host worker11 { hardware ethernet 00:50:56:b7:60:88; fixed-address 172.31.20.88; }
`

**Comment by christianh814** [comment]
The hostname is done via DNS if you're using DHCP for the IP address. The DNS record also has to be in place.

Edit the `/var/named/zonefile.db` and `/var/named/reverse.db` with the entries, change the serial number (on top, it'll have the value of `YYYYMMDDXX` ...it's as simple as just incrementing the number by 1).

Then restart the services (dhcp and named)

**Comment by ragpo** [comment]
thanks, it works, but i want to know how it works with dhcp and named?

**Comment by christianh814** [comment]
> thanks, it works, but i want to know how it works with dhcp and named?

It doesn't. This is a function of RHCOS (which is based on RHEL 8), or any Linux OS in general. The RHCOS host will assign itself the hostname it gets back from the PTR record of the IP.

Hope that makes sense.
