### ISSUE TITLE
Help to generate some machineconfig file (like chrony configuration)

### ISSUE THREAD

**Issue by schabrolles** [RedHatOfficial/ocp4-helpernode#65]
We are currently evaluating the possibility to use this playbook to also generate some useful machineconfig file like ntp (chrony).

- User can specify the chrony.conf need via a variable `chrony_conf` in vars.yaml
```
chrony_conf: |
  server pool.ntp.org iburst
  driftfile /var/lib/chrony/drift
  makestep 1.0 3
  rtcsync
  logdir /var/log/chrony
```

- a template can be used in order to generate the machineconfig file for master and worker with `chrony_conf` encoded with base64

- the results yaml files will be available in a `machineconfig` folder.

- `helpernodecheck install-info` could be updated with the following

```
Quickstart Notes:
        mkdir ~/install
        cd ~/install
        vi install-config.yaml
->      openshift-install create manifests
->      cp ../machineconfig/* ./manifests
        openshift-install create ignition-configs
        cp *.ign /var/www/html/ignition/
        restorecon -vR /var/www/html/
```

Modification seems to work on our side (tested with OCP4.3 on ppc64le PowerVM) and we are ready to propose a PR if you are interested.

**Comment by christianh814** [comment]
I like the idea, but I'm wondering if there's a better way to implement this? I try to avoid too many steps in the quickstart. The idea being to get up and running/installed quickly.

I try to keep most of the "customizations" as a day 2 task.

**Comment by schabrolles** [comment]
I see, but the problem is we faced some issues during installation (with certificates) when time is not synchronized between different physical machines ... 

If you want to have masters not schedulabled, you need to edit a manifest file before creating ignition files

**Comment by christianh814** [comment]
> I see, but the problem is we faced some issues during installation (with certificates) when time is not synchronized between different physical machines ...
> 
> If you want to have masters not schedulabled, you need to edit a manifest file before creating ignition files

Yes, I can see this as a chicken/egg problem ( l’oeuf ou la poule). And it's really one one note about copying the manifests.

Would it be better to have the chrony config as a template? I would think, for the most port, chrony is set up the same...something like this in the vars.yaml

```
chronyconfig:
  - setup: true
    server: pool.ntp.org
    options: iburst
```

Then the template can look like


```
  server {{ chronyconfig.server }} {{chronyconfig.options }}
  driftfile /var/lib/chrony/drift
  makestep 1.0 3
  rtcsync
  logdir /var/log/chrony
```

thoughts?

**Comment by schabrolles** [comment]
> Would it be better to have the chrony config as a template? I would think, for the most port, chrony is set up the same...something like this in the vars.yaml

I thought about it, but because I don’t know all the option we can add into a `chrono.conf` file I preferred let the user giving its own chrono.conf file ... I’m not against your idea (which is cleaner) but it is because I’m not confident enough to fix all the other parameters (we also have to think about several servers to synchronize on, it can be a list, but it become to be complicated)

```
chronyconfig:
  - server: pool1.ntp.org
    options: iburst
 - server: pool2.ntp.org
    options: iburst
```

So, I let you decide ;-)

**Comment by christianh814** [comment]
So here are my thoughts:

The main idea of the helpernode is in giving a "good base" in terms of configurations; and any customizations should be done on day 2.

Anything "complex" is disabled by default. So setting up chrony, my my opinion, falls in this umbrella. So to start, in the default vars file it'll be set to...

```
chronyconfig
  enabled: false
```

So I think we should take  the [example given in the docs](https://docs.openshift.com/container-platform/4.4/installing/install_config/installing-customizing.html#installation-special-config-crony_installing-customizing) and create the config on it.

So a user can add this to their `vars.yaml` to something like this

```
chronyconfig:
  enabled: true
  - server: pool1.ntp.org
    options: iburst
  - server: pool2.ntp.org
    options: iburst
```
Then in the template...

```
{% for c in chronyconfig %}
server {{ chronyconfig.server }} {{chronyconfig.options }}
{% endfor %}
driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
logdir /var/log/chrony
```

Or however it ends up. If the user needs to modify this file, they can do it before loading into the manifests or post install.

**Comment by schabrolles** [comment]
@christianh814, how do you pass the template to b64encode filter ?

We are already using a template for the machineconfig file which use the chrony_conf variable (block of text) to be b64encode (see #67) ... I don’t know how I can do that easily if `chrony.conf` is also a template.

We we propose this is because :
 - we think chrony must be in place before starting cluster installation
 - It is really painful for new user to deal with machineconfig file due to base64 encoding inside yaml (ansible helps here)

In the proposed PR (#67), chrony configuration will be generated if the user specify a chrony_conf variable in vars.yaml (a example is provided, but commented by default)

**Comment by christianh814** [comment]
@schabrolles So after thinking about this I've come to the conclusion...

1) Setting up chrony is definitely something that will be useful. Especially in places where not all networks are NAT-ed or are blocked from reaching `clock.redhat.com`
2) I like templatizing the machineconfig like how you have it in #67 
3) I'm against just dropping a file in the `vars.yaml`

The reason for 3 is because it goes against the pattern already established. How I would modify this is that you'll need another two tasks. 1 That creates the actual chrony.conf file (so maybe another template file) then load the resulting file somewhere (/usr/local/src/ is what I've been using). Then slurp that file into a var to use in your machineconfig. It's basically what you have in #67 but adding two more tasks

For example:

I have this template
```
this is base64 encoded "{{ data['content'] }}"
```
This is the playbook I have

```yaml
- hosts: all
  tasks:
    
    - name: create a file however you want, I suggest a template
      shell: echo hi > /tmp/chrony.test
    
    - name: slurp contents of file
      slurp:
        src: /tmp/chrony.test
      register: data
  
    - name: base64 that into a file
      template:
        src: sample.txt.j2
        dest: sample.txt
```

The outcome was sample.txt with...

```
this is base64 encoded "aGkK"
```

Checking it, yes that's the encoding

```shell
echo -n 'aGkK' | base64 -d
hi
```

**Comment by schabrolles** [comment]
Hehe 🤣.... ok. Then I will give it a “slurp” tomorrow.
