### ISSUE TITLE
OC login failed in master node

### ISSUE THREAD

**Issue by rahulsingh45-tech** [RedHatOfficial/ocp4-helpernode#73]
I have installed RHCOS . i have login to master node where oc login failing with below error.
[core@master0 openshift]$ oc login -u system:admin --insecure-skip-tls-verify
Server [https://localhost:8443]: https://api.ocp4.bacadgsl.com:6443
error: net/http: TLS handshake timeout

Also please find below output of oc command.
[core@master0 openshift]$ oc version
Client Version: 4.3.7-202003130552-62c8cca

**[core@master0 openshift]$ oc status
error: Missing or incomplete configuration info. Please login or point to an existing, complete config file:

Via the command-line flag --config
Via the KUBECONFIG environment variable
In your home directory as ~/.kube/config
To view or setup config directly use the 'config' command.**

Please help to resolve the same.

**Comment by christianh814** [comment]
Looking at your prompt...

```
[core@master0 openshift]$ oc login -u system:admin --insecure-skip-tls-verify
Server [https://localhost:8443]: https://api.ocp4.bacadgsl.com:6443
error: net/http: TLS handshake timeout
```

Don't login on the master. Meaning **DON'T** ssh into the master and run the `oc` commands. Run the `oc` commands from the helper.
