### ISSUE TITLE
Worker node gave error message "Internal Server Error" during OCP 4.4.5 installation

### ISSUE THREAD

**Issue by mransonwang** [RedHatOfficial/ocp4-helpernode#74]
ignition[889] GET https://api-int.ocp4.example.com:22623/config/worker attempt #26
ignition[889] GET result: Internal Server Error

There's no such error message on OCP 4.3 version.

**Comment by christianh814** [comment]
We haven't tested on 4.4.5, please use 4.4.3 (which is the default on this playbook).
