### ISSUE TITLE
imageregistry operator is not activated by default (at least on ppc64le)

### ISSUE THREAD

**Issue by schabrolles** [RedHatOfficial/ocp4-helpernode#76]
Here is the output of the `oc get configs.imageregistry.operator.openshift.io -o yaml` we got on Power (ppc64le) after having install OCP 4.3.18

```
apiVersion: v1
items:
- apiVersion: imageregistry.operator.openshift.io/v1
  kind: Config
  metadata:
    creationTimestamp: « 2020-05-25T14:23:48Z »
    finalizers:
    - imageregistry.operator.openshift.io/finalizer
    generation: 1
    name: cluster
    resourceVersion: « 20362 »
    selfLink: /apis/imageregistry.operator.openshift.io/v1/configs/cluster
    uid: 1fc4933c-d0d7-41cd-b404-eb592fa443f4
  spec:
    defaultRoute: false
    disableRedirect: false
    httpSecret: a0f3f4a62c08efb15777319adc01524ea6a51437c2e48a3e076b7d81815a04fa37469116b2d8dcdaaad42e35829de30da76344b257b48a9e03fc2daeee67c878
    logging: 2
    managementState: Removed
    proxy:
      http: «  »
      https: «  »
      noProxy: «  »
    readOnly: false
    replicas: 1
    requests:
      read:
        maxInQueue: 0
        maxRunning: 0
        maxWaitInQueue: 0s
      write:
        maxInQueue: 0
        maxRunning: 0
        maxWaitInQueue: 0s
    storage: {}
  status:
    conditions:
    - lastTransitionTime: « 2020-05-25T14:47:48Z »
      message: All registry resources are removed
      reason: Removed
      status: « False »
      type: Progressing
    - lastTransitionTime: « 2020-05-25T14:23:49Z »
      message: The registry is removed
      reason: Removed
      status: « True »
      type: Available
    - lastTransitionTime: « 2020-05-25T14:23:49Z »
      status: « False »
      type: Degraded
    - lastTransitionTime: « 2020-05-25T14:23:49Z »
      message: The registry is removed
      reason: Removed
      status: « True »
      type: Removed
    observedGeneration: 1
    readyReplicas: 0
    storage: {}
    storageManaged: false
kind: List
metadata:
  resourceVersion: «  »
  selfLink: «  »
```

It seems that `managementState: Removed`  (don’t know if it is the same for x86 on ocp4.3...). 
But this mean we should first patch this is order to activate the operator to have the registry being deployed.

`oc patch configs.imageregistry.operator.openshift.io cluster —type merge —patch ‘{« spec »:{« managementState »: « Managed »}}’`

This patch could be added to the documentation provided by the `ocp4helperchek nfs-info` command, as it should be always like this... (should be managed)

Then we can patch the storage to use a real PV ...

```
oc patch configs.imageregistry.operator.openshift.io cluster --type=json -p '[{"op": "remove", "path": "/spec/storage/emptyDir" }]'
oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{ "claim": "registry-pvc"}}}}'
```

**Comment by bpradipt** [comment]
It's the same for all platforms. It's documented as well.
https://docs.openshift.com/container-platform/4.3/installing/installing_bare_metal/installing-bare-metal.html#registry-removed_installing-bare-metal
https://github.com/openshift/installer/blob/master/docs/user/power/install_upi.md#watching-your-installation

**Comment by christianh814** [comment]
As @bpradipt pointed out, this is already documented and covered in the [ppc64le quickstart](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/quickstart-ppc64le.md#finish-install)

Closing this as not-a-bug

**Comment by schabrolles** [comment]
@christianh814 @bpradipt ... happy to hear it is not a bug and documented somewhere... but I think it could be could to also update `helpernodecheck nfs-info` accordingly.

What do you think ?

```
An NFS server has been installed and the entire /export directory has been shared out. To set up the nfs-auto-provisioner; you just need to run the following command after "openshift-install wait-for bootstrap-complete --log-level debug" has finished...

	helpernodecheck nfs-setup

Thats it! Right now, this is an "opinionated" setup (there is no "how do I set this up for..."). For now, this is what you get.

Once it's setup, create a PVC for the registry (an example of one has been provided)

	oc create -f /usr/local/src/registry-pvc.yaml -n openshift-image-registry

Check that with "oc get pv" and "oc get pvc -n openshift-image-registry".

Then set the registry to use this NFS volume. (you may need to remove the emptyDir if you set it beforehand)

	oc patch configs.imageregistry.operator.openshift.io cluster --type=json -p '[{"op": "remove", "path": "/spec/storage/emptyDir" }]'
	oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{ "claim": "registry-pvc"}}}}'


Check the status by watching "oc get pods -n openshift-image-registry"
```

**Comment by christianh814** [comment]
I do think this needs to be updated since we've made this more configurable. 

What do you suggest we add?

**Comment by schabrolles** [comment]
I think we need to have the procedure with the patch updated.

- operator has to be activated:
`oc patch configs.imageregistry.operator.openshift.io cluster —type merge —patch ‘{« spec »:{« managementState »: « Managed »}}’`

and `oc patch configs.imageregistry.operator.openshift.io cluster --type=json -p '[{"op": "remove", "path": "/spec/storage/emptyDir" }]' ` can be removed (as noting is configured because operator is not in managed state.

**Comment by christianh814** [comment]
@schabrolles 

So I like this, generally speaking.

However the only reason `oc patch configs.imageregistry.operator.openshift.io cluster --type=json -p '[{"op": "remove", "path": "/spec/storage/emptyDir" }]'` is there, is because someone might be following the "quickstart" guide(s). Which means they would have set the `emptyDir`, which means they need to remove it first.
