### ISSUE TITLE
Approach to create rhcos master & worker machine

### ISSUE THREAD

**Issue by rahulsingh45-tech** [RedHatOfficial/ocp4-helpernode#78]
Hi, 

I have created rhcos bootstrap machine using "bootstrap.ign" file. Now I want to create a master and a worker machine but the steps for this is not clearly mentioned anywhere.  Can you please confirm if we can follow the below approach:
"Create master and worker machine in the same way bootstrap node was created,instead will provide "master.ign" for master machine and "worker.ign" file for worker machine during first boot."

Or pls suggest if need to follow any other method.

**Comment by christianh814** [comment]
Installing RHCOS is the same procedure regaurdless if it's bootstrap, master, or worker. You just need to provide the appropriate `coreos` kernel parameters (which includes the ignition files).

**Comment by rahulsingh45-tech** [comment]
Hi,
While creating rhcos master node , install is completed ,after reboot it again redirect to the Kernel command window (TAB window) and then when i pressed Enter key , it get failed with below error:
dracut initqueue: warning dhcp for interface eth0 failed 
rtnetlink answers : file exists

I am using static ip method in kernel command argument.

In below screenshot , it says install complete.
![install_complete](https://user-images.githubusercontent.com/64540939/83641495-4010ac00-a5cb-11ea-9908-3d465aa2b39b.jpg)

Then dhcp failed error:

![dhcp failed](https://user-images.githubusercontent.com/64540939/83641650-70f0e100-a5cb-11ea-9c0b-103ad7456736.jpg)

At last , boot failed error
![boot failed](https://user-images.githubusercontent.com/64540939/83641734-8b2abf00-a5cb-11ea-9700-1c5aaf1d20ce.jpg)

**Comment by christianh814** [comment]
You need to make sure the DVD installer "ejects" the DVD after the install completes

**Comment by rahulsingh45-tech** [comment]
I am not using CD/DVD , loaded ISO image file instead. Do i need to remove this file after install completes ?

**Comment by christianh814** [comment]
> I am not using CD/DVD , loaded ISO image file instead. Do i need to remove this file after install completes ?

yes you need to detatch the ISO when the install completes.

**Comment by bpradipt** [comment]
You can also define the boot order as disk and cd to start with (when disk is empty). This will ensure that when the install via iso is successful, the reboot will boot from the disk (first one in the boot order).

**Comment by rahulsingh45-tech** [comment]
Thanks Christian for the help. Issue is resolved and successfully created the master node. 
Now , getting below error while creating worker node.

Install completed , detatch the ISO and then getting below error for worker node.

![worker_node_issue](https://user-images.githubusercontent.com/64540939/83666731-09e32480-a5eb-11ea-99a3-dc3d31ca71a6.jpg)

**Comment by rahulsingh45-tech** [comment]
Can i go with 1 bootstrap , 1 master and 2 worker node ?  If yes , then I had already boot 1 master node.

**Comment by christianh814** [comment]
> Can i go with 1 bootstrap , 1 master and 2 worker node ? If yes , then I had already boot 1 master node.

No, the minimum required us 1 bootstrap, 3 masters, and 2 workers. This is outlined in the [official docs](https://docs.openshift.com/container-platform/4.4/installing/installing_bare_metal/installing-bare-metal.html#machine-requirements_installing-bare-metal)

**Comment by rahulsingh45-tech** [comment]
Yes , I had read that doc earlier. I thought if I provide replica value as 1 in install-config.yaml file just like below , would be able to go with 1 master node.  Now , if I create 3 master node , will it work ? or Should I create the new install-config.yaml file and again generate ignition config files ?

apiVersion: v1
baseDomain: RHCOSDGSL
compute:
- hyperthreading: Enabled
 name: worker
 replicas: 0 
controlPlane:
 hyperthreading: Enabled
 name: master
 replicas: 1

**Comment by rahulsingh45-tech** [comment]
Okay. I will go with recommended approach (ie. 3 master node). In that case ,have to create new install-config.yaml file to update replica number.

Can you help me with the below cidr concept in defining values of cidr & servicenetwork ip. The description is not very clear in doc.

![cidr concept](https://user-images.githubusercontent.com/64540939/83785422-e71a4400-a6ae-11ea-8051-ab11d669f83d.jpg)

**Comment by christianh814** [comment]
Those options are for the SDN and Pod networks. This is an overlay network that gets installed.

* `clusterNetwork.cidr` - This is the network that you're assigning for the pods to have
* `serviceNetwork` - this is the network range that will be assigned to the service network

All that you need to make sure of is that this doesn't overlap with the network you're on. 

If you'd like to read more about Kubernetes networking concepts, this is a [good blog to start](https://medium.com/google-cloud/understanding-kubernetes-networking-pods-7117dd28727)

**Comment by rahulsingh45-tech** [comment]
Thanks Christian. This is very useful. 
Do you have any idea as why at least 3 master node is required for rhcos ,  instead of 1 master node.
How and what work will get distribute to each master node.

**Comment by christianh814** [comment]
> Do you have any idea as why at least 3 master node is required for rhcos , instead of 1 master node.

This is because ETCd needs 3 nodes to reach quorum. You can read more about it [here](https://kubernetes.io/docs/concepts/overview/components/#etcd)

> How and what work will get distribute to each master node.

The OpenShift API, Kubneretes API, the Controller Manager, and The Scheduler all run on the Masters. ETCD is also ran on the masters as a static node.

The masters are labeled with `node-role.kubernetes.io/master` and have a [taint](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) on them to repel other workloads.

**Comment by rahulsingh45-tech** [comment]
I have created new "install-config.yaml" and ignition config files and then recreated a bootstrap and 3 master node.  Two master nodes boot completes successfully but one master (Master1) node boot is failing with below error:

![master1_node_issue](https://user-images.githubusercontent.com/64540939/84033683-e0454700-a9b6-11ea-8a59-a6ddd04a8f9a.jpg)

**Comment by christianh814** [comment]
This is not enough information to go off of. But I suspect that you probably didn't regenerate the ignition files.

The ignition files doesn't have a long life. Always regenerate them after a failed install attempt.

**Comment by rahulsingh45-tech** [comment]
I had regenerated the ignition files. and 2 master node (master2 ,master3) boot was also completed. This issue is only with 1 master node (master1) , in which rhcos install completes but boot is getting failed after that(after detatch the iso file). 
This is little surprising because other two master node completed successfully using same ignition file ("master.ign").

For troubleshooting , I tried same request on bootstrap node and one of the master node, it seems SSL Error on Bootstrap node while making SYSCALL to helpernode(10.254.9.60). On one of the master node(master2), didn't observe SSL errors.
NOTE: 10.254.9.60 is the helpernode.

**Bootstrap Node:**
[core@localhost ~]$ curl -vk https://api-int.ocp4.bacadgsl.com:22623/
*   Trying 10.254.9.60...
* TCP_NODELAY set
* Connected to api-int.ocp4.bacadgsl.com (10.254.9.60) port 22623 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api-int.ocp4.bacadgsl.com:22623 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api-int.ocp4.bacadgsl.com:22623 


**Master Node (master2)**
[core@localhost ~]$ curl -vk https://api-int.ocp4.bacadgsl.com:22623/
*   Trying 10.254.9.60...
* TCP_NODELAY set
* Connected to api-int.ocp4.bacadgsl.com (10.254.9.60) port 22623 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api-int.ocp4.bacadgsl.com
*  start date: May  5 14:03:38 2020 GMT
*  expire date: Jun  3 13:05:04 2030 GMT
*  issuer: OU=openshift; CN=root-ca
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5621d61fe700)
> GET / HTTP/2
> Host: api-int.ocp4.bacadgsl.com:22623
> User-Agent: curl/7.61.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404 
< content-length: 0
< date: Mon, 08 Jun 2020 13:58:32 GMT
< 
* Connection #0 to host api-int.ocp4.bacadgsl.com left intact

**Comment by christianh814** [comment]
There's something wrong in your config or with how you're booting up/installing CoreOS

`core@localhost`

^ it shouldn't say that in your prompt. Not if you're using the playbook correctly.

**Comment by rahulsingh45-tech** [comment]
Now ,I have manually changed the hostname of Bootstrap & Master node to their respective name but after reboot again automatically changed to "localhost". This is the Transient hostname(Received from network configuration).

I think there might be some DNS configuration issue in helperNode.

**Comment by christianh814** [comment]
> I think there might be some DNS configuration issue in helperNode.

Double check your DNS configs and double check your `ip=` syntax.

**Comment by rahulsingh45-tech** [comment]
Passing below parameter in kernel command:
ip=10.254.9.64::10.254.8.1:255.255.254.0:master0:eth0:none nameserver=10.254.9.60

Attached the 10.254.9.60:9000 page status here:
[Statistics Report for HAProxy.pdf](https://github.com/RedHatOfficial/ocp4-helpernode/files/4763526/Statistics.Report.for.HAProxy.pdf)

**Comment by christianh814** [comment]
Two things I see...

> 255.255.254.0

As I [stated before](https://github.com/RedHatOfficial/ocp4-helpernode/issues/55#issuecomment-627452855), this playbook only supports a `/24` networkspace (i.e. 255.255.255.0).  This is a known bug #2 

However, that being said, since you're using static IPs it shouldn't matter too much. I'm not 100% sure. Needs more testing.

Another this is...

> master0

Try setting that to the FQDN...so something like this...

```
ip=10.254.9.64::10.254.8.1:255.255.254.0:master0.ocp4.bacadgsl.com:eth0:none nameserver=10.254.9.60
```

Try doing this for all nodes in the cluster on install.

**Comment by rahulsingh45-tech** [comment]
Yes , I was also thinking of FQDN in hostname parameter in kernel command. I will try this for sure.

**Comment by rahulsingh45-tech** [comment]
I have tried boot with hostname parameter "master0.ocp4.bacadgsl.com " and also tried "master0.bacadgsl.com" but still getting the same error in master0 node.  Now, what should be the next steps to troubleshoot further this issue.

What does EOF means in error ?

**Comment by christianh814** [comment]
> What does EOF means in error ?

This means that the API/machineconfig service isn't up yet or is crashing. Which, initially, runs on the bootstrap.

> Now, what should be the next steps to troubleshoot further this issue.

Login to the bootstrap and see what you see in the logs by running `journalctl -f`

**Comment by rahulsingh45-tech** [comment]
Here are the logs: I can see msg  "approve-csr :connection to the server was refused" in logs

-- Logs begin at Thu 2020-06-11 15:51:16 UTC. --
Jun 11 18:08:25 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:25.937069    1783 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Jun 11 18:08:25 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:25.941447    1783 kubelet_node_status.go:472] Recording NodeHasSufficientMemory event message for node bootstrap.bacadgsl.com
Jun 11 18:08:25 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:25.941499    1783 kubelet_node_status.go:472] Recording NodeHasNoDiskPressure event message for node bootstrap.bacadgsl.com
Jun 11 18:08:25 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:25.941520    1783 kubelet_node_status.go:472] Recording NodeHasSufficientPID event message for node bootstrap.bacadgsl.com
Jun 11 18:08:35 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:35.948855    1783 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Jun 11 18:08:35 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:35.952482    1783 kubelet_node_status.go:472] Recording NodeHasSufficientMemory event message for node bootstrap.bacadgsl.com
Jun 11 18:08:35 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:35.952530    1783 kubelet_node_status.go:472] Recording NodeHasNoDiskPressure event message for node bootstrap.bacadgsl.com
Jun 11 18:08:35 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:35.952549    1783 kubelet_node_status.go:472] Recording NodeHasSufficientPID event message for node bootstrap.bacadgsl.com
Jun 11 18:08:38 bootstrap.bacadgsl.com approve-csr.sh[1802]: The connection to the server localhost:6443 was refused - did you specify the right host or port?
Jun 11 18:08:41 bootstrap.bacadgsl.com podman[55784]: 2020-06-11 18:08:41.017905484 +0000 UTC m=+30.043300305 container remove e636c7c29bdbd7f2f0e771631be3c12b604fc16c1a1b418aa249fb3176151667 (image=quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61, name=focused_kepler)
Jun 11 18:08:43 bootstrap.bacadgsl.com podman[55939]: 2020-06-11 18:08:43.025572847 +0000 UTC m=+1.033528579 container create 4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4 (image=quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61, name=vigilant_murdock)
Jun 11 18:08:43 bootstrap.bacadgsl.com systemd[1]: Started libpod-conmon-4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4.scope.
Jun 11 18:08:43 bootstrap.bacadgsl.com systemd[1]: Started libcontainer container 4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4.
Jun 11 18:08:43 bootstrap.bacadgsl.com kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Jun 11 18:08:43 bootstrap.bacadgsl.com podman[55939]: 2020-06-11 18:08:43.733684644 +0000 UTC m=+1.741640376 container init 4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4 (image=quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61, name=vigilant_murdock)
Jun 11 18:08:44 bootstrap.bacadgsl.com podman[55939]: 2020-06-11 18:08:44.029050569 +0000 UTC m=+2.037006401 container start 4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4 (image=quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61, name=vigilant_murdock)
Jun 11 18:08:44 bootstrap.bacadgsl.com podman[55939]: 2020-06-11 18:08:44.029844092 +0000 UTC m=+2.037799824 container attach 4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4 (image=quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61, name=vigilant_murdock)
Jun 11 18:08:44 bootstrap.bacadgsl.com systemd[1]: libpod-4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4.scope: Consumed 819ms CPU time
Jun 11 18:08:44 bootstrap.bacadgsl.com podman[55939]: 2020-06-11 18:08:44.465914329 +0000 UTC m=+2.473870061 container died 4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4 (image=quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61, name=vigilant_murdock)
Jun 11 18:08:45 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:45.959877    1783 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Jun 11 18:08:45 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:45.963926    1783 kubelet_node_status.go:472] Recording NodeHasSufficientMemory event message for node bootstrap.bacadgsl.com
Jun 11 18:08:45 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:45.963971    1783 kubelet_node_status.go:472] Recording NodeHasNoDiskPressure event message for node bootstrap.bacadgsl.com
Jun 11 18:08:45 bootstrap.bacadgsl.com hyperkube[1783]: I0611 18:08:45.963990    1783 kubelet_node_status.go:472] Recording NodeHasSufficientPID event message for node bootstrap.bacadgsl.com
Jun 11 18:08:50 bootstrap.bacadgsl.com podman[55939]: 2020-06-11 18:08:50.8388442 +0000 UTC m=+8.846799932 container remove 4509b004e409d51b3bce2d9221c70c9c502fde077762be1d1306f9acffdfcbf4 (image=quay.io/openshift-release-dev/ocp-release@sha256:e1ebc7295248a8394afb8d8d918060a7cc3de12c491283b317b80b26deedfe61, name=vigilant_murdock)

**Comment by christianh814** [comment]
> Jun 11 18:08:38 bootstrap.bacadgsl.com approve-csr.sh[1802]: The connection to the server localhost:6443 was refused - did you specify the right host or port?

Means the api isn't starting for whatever reason.

> bootstrap.bacadgsl.com 

This name is wrong so double check your `ip=`

**Comment by rahulsingh45-tech** [comment]
I did tried with name "bootstrap.ocp4.bacadgsl.com" also , not sure what is missing.

**Comment by christianh814** [comment]
Have you tried installing it on a network space that's `/24`?

Looks like you're virtualizing it, so it should be trivial to change.

**Comment by rahulsingh45-tech** [comment]
Yes , I have tried on /24 network space as well. 
After deep analysis , I have observed something very interesting as mentioned below:

-- Able to boot master node using ignition files which were created before ansible-playbook script run, but this ignition contains wrong replica number ie.2 it should be 0. Is there any possibility to directly change worker replicas value in ignition file ?
-- Compared ignition files before & after ansible-playbook script run. Its been observed that bootstrap Ignition file is not same even both generated through same install-config.yaml file. Does ansible script changed any openshift files  due to which new bootstrap ignition file is not same as old one ?
-- Re-installed Openshift and OC CLI , then created ignition files but still getting same errors.

What is your opinion in this ?

**Comment by rahulsingh45-tech** [comment]
Can someone  pls help me here.

**Comment by christianh814** [comment]
> Yes , I have tried on /24 network space as well.
> After deep analysis , I have observed something very interesting as mentioned below:
> 
> -- Able to boot master node using ignition files which were created before ansible-playbook script run, but this ignition contains wrong replica number ie.2 it should be 0. Is there any possibility to directly change worker replicas value in ignition file ?

This wouldn't be changed in the ignition file. You'd change this when you run `openshift-install create manifest` and delete the machineset it creates. It's easier to just delete the ignition files and recreate them.

The ignition files created are only good for 24 hours anyway.

> -- Compared ignition files before & after ansible-playbook script run. Its been observed that bootstrap Ignition file is not same even both generated through same install-config.yaml file. Does ansible script changed any openshift files due to which new bootstrap ignition file is not same as old one ?

The ansible playbook doesn't do anything with the `install-config.yaml` file nor does it do anything with the ignition files.

That being said, every time your run `openshift-install create ignition-configs`, it'll generate a different ignition file. Doesn't matter that you're using the same `install-config.yaml` file. This is because it generates certificates on creation.

> -- Re-installed Openshift and OC CLI , then created ignition files but still getting same errors.
> 
> What is your opinion in this ?

Your errors seem environmental. Not sure what's going on without more info about your specific setup.

**Comment by rahulsingh45-tech** [comment]
Is there any way to identify from ignition file that what parameters (like cidr, serviceNetwork, hostPrefix etc.) were used in install-config.yaml. It seems like ignition files are encrypted , any way to decrypt/ capture those details ?

During analysis, i have observed that ignition files are same generated each time through same install-config.yaml after ansible-playbook script run.  But it differs with ignition files (bootstrap.ign) which were generated before ansible-playbook script run.

**Comment by christianh814** [comment]
> Is there any way to identify from ignition file that what parameters (like cidr, serviceNetwork, hostPrefix etc.) were used in install-config.yaml. It seems like ignition files are encrypted , any way to decrypt/ capture those details ?

You can take a look at the ignition files with `jq`. You can run something like...

```
jq -r < bootstrap.ini
```

The entries are not encrypted, they are base64 encoded. Just take the encoding and pipe it through `base64 -d`. For example...

```
echo -n 'RG8geW91ciBob21ld29yawo=' |base64 -d
```

> During analysis, i have observed that ignition files are same generated each time through same install-config.yaml after ansible-playbook script run. But it differs with ignition files (bootstrap.ign) which were generated before ansible-playbook script run.

The playbook does not touch the ignition files. Point to where it does this (i.e. link to the code) and I'll take a look to see if it does.

**Comment by christianh814** [comment]
Closing stale issue
