### ISSUE TITLE
RFE: Add prometheus exporters on Helpernode to monitor on OCP

### ISSUE THREAD

**Issue by samueltauil** [RedHatOfficial/ocp4-helpernode#88]
I think would be interesting to add prometheus exporters to httpd, bind and such so we could monitor metrics from helpernode in OCP (maybe a dedicated namespace with prometheus/grafana instances)

**Comment by christianh814** [comment]
@samueltauil Do you think this would be useful? https://github.com/prometheus/haproxy_exporter

**Comment by samueltauil** [comment]
yes also there are others for bind and dhcp and so on: 
https://github.com/kumina/libvirt_exporter
https://github.com/prometheus-community/bind_exporter
https://github.com/Lusitaniae/apache_exporter
https://github.com/prometheus/haproxy_exporter

**Comment by christianh814** [comment]
This will probably go into V2
