### ISSUE TITLE
Can OCP4.3 support ppc64le baremetal server?

### ISSUE THREAD

**Issue by zet809** [RedHatOfficial/ocp4-helpernode#89]
We have several IBM power8/power9 OpenPOWER servers(which bootloader is petitboot)

When deploy CoreOS on it, install process completed successfully. But when server reboot, it can not boot from harddisk as petitboot can not parse out configuration.

BTW, if deploy CoreOS on KVM based VMs on one of these servers, it can be loaded successfully as VM use grub2 as bootloader.

So, the question is, whether OpenPOWER baremetal server is supported by OCP4.3 and higher? Thx!

**Comment by zet809** [comment]
Furthermore, a quickly question that as we have bound NVIDIA GPU for the VMs, from VM, the GPU device are available. But we can not find any document about setup GPU for OCP4.3 on ppc64le cluster, will you pls point me to the right link? Thx!

**Comment by bpradipt** [comment]
@zet809 baremetal deployment on OpenPower servers is supported.  @manojnkumar should be able to provide additional information on baremetal and GPU support

btw, I believe these questions are more suited for https://github.com/openshift/installer or https://github.com/openshift/openshift-docs/issues

**Comment by manojnkumar** [comment]
@zet809 : It depends on the server.  Most of the P9 servers have the fix for this issue https://bugzilla.linux.ibm.com/show_bug.cgi?id=182251 available in petitboot/firmware, or at least you can update with the fix.   Some of the P8s do not have this fix made available.

**Comment by zet809** [comment]
Thanks @manojnkumar @bpradipt , I will ask our admin to update Firmware mentioned above and let you know the results!

**Comment by bpradipt** [comment]
@zet809 can this issue can be closed ?

**Comment by zet809** [comment]
Thx, @bpradipt
