### ISSUE TITLE
adding others in vars.yaml leads to creating pxeconfigs for them also if using DHCP

### ISSUE THREAD

**Issue by walidbahgat** [RedHatOfficial/ocp4-helpernode#91]
when adding any host to others in vars.yaml, it creates a pxeconfig for it

**Comment by therevoman** [comment]
Looking at the code, a pxeconfig does not get generated for servers listed in "other".  However, there is a "default" pxeconfig file which gets generated and is probably interfering if "Network Boot" is high enough in the priority for those systems.  

Question becomes, if a `vars.yaml` attribute is added, should the current behavior be the default or should the default behavior exclude creation of a "default" pxeconfig?
@christianh814

**Comment by therevoman** [comment]
Decided to change the default behavior, and not generate a `default` pxe config.

**Comment by christianh814** [comment]
> Decided to change the default behavior, and not generate a `default` pxe config.

I agree. The priority is to have masters/workers/bootstrap "auto pxe booted".

**Comment by christianh814** [comment]
Closed by #99 in `devel`
