### ISSUE TITLE
Please add ip=eno3:dhcp option to the dhcp server config files

### ISSUE THREAD

**Issue by gefrickel** [RedHatOfficial/ocp4-helpernode#92]
Hi, please allow the addition of the ip=eno3:dhcp option to the dhcp server config files to allow for more flexibility in the bare metal upi deployment.

I envision that it could be an option of the vars.yaml. That would be very helpfull.

e.g.

default menu.c32
 prompt 1
 timeout 9
 ONTIMEOUT 1
 menu title ######## PXE Boot Menu ########
 label 1
 menu label ^1) Install Bootstrap Node
 menu default
 kernel rhcos/kernel
 append initrd=rhcos/initramfs.img nomodeset **ip=eno3:dhcp** rd.neednet=1 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://10.0.0.250:8080/install/bios.raw.gz coreos.inst.ignition_url=http://10.0.0.250:8080/ignition/bootstrap.ign

Greetings and thanks.

**Comment by christianh814** [comment]
Good catch! Although I think just setting `ip=dhcp` is generic enough to where it'll work for all platforms. Anyway, this is an easy enough fix.

**Comment by christianh814** [comment]
Closed by #127
