### ISSUE TITLE
add more parameters to the documentation about the vars.yaml

### ISSUE THREAD

**Issue by walidbahgat** [RedHatOfficial/ocp4-helpernode#95]
maybe we need to document more options the vars.yaml already can handle
such as chrony and opc_bios that can handle both urls and local files

**Comment by christianh814** [comment]
The notes about [chrony](https://github.com/RedHatOfficial/ocp4-helpernode/blob/devel/docs/vars-doc.md#ntp-configuration) and [ocp local artifacts](https://github.com/RedHatOfficial/ocp4-helpernode/blob/devel/docs/vars-doc.md#specifying-artifacts) are now on the `devel` branch.
