### ISSUE TITLE
ppc64le conditionals cause problems on ARM

### ISSUE THREAD

**Issue by therevoman** [RedHatOfficial/ocp4-helpernode#98]
I'm using the helpernode for services on a mini k8s ARM cluster.  Because its k8s and not OpenShift some of the other issues don't apply here, but the ppc64le conditionals cause problems when trying to use this on the arm architecture.  Not sure if this will affect any other architectures, but I'll add more detail next time I'm on my ARM cluster.

**Comment by bpradipt** [comment]
@therevoman please do mention the issues when you retry and we can work on fixing the issues.

**Comment by christianh814** [comment]
@therevoman Although OCP support isn't coming to ARM any time soon...installing the helper should "just work"  (granted the right pkgs are available and python is set correctly) on ARM, so I'm keeping this open for curiosity sake.

**Comment by christianh814** [comment]
Closing stale issues
